In [1]:
import random
random.seed(42)

import torch

import numpy as np
import pyomo.environ as pyo
import pandas as pd
import matplotlib.pyplot as plt

from pyomo.environ import *
from utils import generate_simple_synthetic_data, const_embed, load_case_study_data
from trainer import Trainer

np.random.seed(43)

LOAD_CASE_STUDY = False

In [2]:
if not LOAD_CASE_STUDY:
    X, y, true_mean, true_std = generate_simple_synthetic_data(n_samples=1000)

    print(X.head())
    print(y.head())
else:
    print("Loading case study data...")
    X, y, val_ind, test_ind = load_case_study_data()

         x1        x2      price
0  0.374540  0.185133  15.234114
1  0.950714  0.541901  14.939576
2  0.731994  0.872946  28.125092
3  0.598658  0.732225  14.990924
4  0.156019  0.806561  15.438995
0    4.164115
1    9.161541
2    0.433392
3    5.661846
4    5.218591
Name: y, dtype: float64

In [3]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

'''model_config = {
    'hidden_layers': 1,
    'hidden_size': 5,
    'drop': 0.2
    }

training_config = {
    'lr': 0.01,
    'wd': 0.0001,
    'batchsize': 64,
    'iters': 500,
    'patience': 20
    }'''

config = {
    # Model config
    'hidden_layers': 0,
    'hidden_size': 50,
    'drop': 0.05,

    # Training config
    'lr': 0.001,
    'wd': 0,
    'batchsize': 64,
    'iters': 5000,
    'patience': 1000
}

n_preds = 1

trainer = Trainer(X, y, config, n_preds=n_preds, device=device)

if LOAD_CASE_STUDY:
    trainer.set_data_partitions(X_train=X[(~X.index.isin(val_ind)) & (~X.index.isin(test_ind))], y_train=y[(~y.index.isin(val_ind)) & (~y.index.isin(test_ind))], X_val=X[X.index.isin(val_ind)], y_val=y[y.index.isin(val_ind)], X_test=X[X.index.isin(test_ind)], y_test=y[y.index.isin(test_ind)])
else:
    trainer.create_data_partitions(val_size=0.2, test_size=0.2, random_state=42)

print("X_train shape: ", trainer.X_train.shape)
print("X_val shape: ", trainer.X_val.shape)
print("X_test shape: ", trainer.X_test.shape)

trainer.train()

trainer.test()

X_train shape:  (600, 3)
X_val shape:  (200, 3)
X_test shape:  (200, 3)
Validation loss improved from inf to 255778.7188 in epoch 1. Saving model...
Epoch 1/5000 - Train Loss: 345188.1842, Val Loss: 255778.7188
Validation loss improved from 255778.7188 to 182410.4219 in epoch 2. Saving model...
Validation loss improved from 182410.4219 to 139060.2812 in epoch 3. Saving model...
Validation loss improved from 139060.2812 to 87810.0703 in epoch 4. Saving model...
Validation loss improved from 87810.0703 to 56504.6172 in epoch 5. Saving model...
Validation loss improved from 56504.6172 to 26517.2617 in epoch 6. Saving model...
Validation loss improved from 26517.2617 to 15104.8799 in epoch 7. Saving model...
Validation loss improved from 15104.8799 to 9747.0762 in epoch 8. Saving model...
Validation loss improved from 9747.0762 to 8909.9551 in epoch 9. Saving model...
Validation loss improved from 8909.9551 to 7495.8228 in epoch 10. Saving model...
Validation loss improved from 7495.8228 to 6121.1963 in epoch 11. Saving model...
Epoch 11/5000 - Train Loss: 5963.7981, Val Loss: 6121.1963
Validation loss improved from 6121.1963 to 5362.1436 in epoch 12. Saving model...
Validation loss improved from 5362.1436 to 4461.7241 in epoch 13. Saving model...
Validation loss improved from 4461.7241 to 3854.9402 in epoch 14. Saving model...
Validation loss improved from 3854.9402 to 3322.6624 in epoch 15. Saving model...
Validation loss improved from 3322.6624 to 3296.2964 in epoch 16. Saving model...
Validation loss improved from 3296.2964 to 3272.1299 in epoch 17. Saving model...
Validation loss improved from 3272.1299 to 1389.5792 in epoch 18. Saving model...
Validation loss improved from 1389.5792 to 1133.9386 in epoch 19. Saving model...
Validation loss improved from 1133.9386 to 1034.3956 in epoch 20. Saving model...
Validation loss improved from 1034.3956 to 985.5173 in epoch 21. Saving model...
Epoch 21/5000 - Train Loss: 2010.3817, Val Loss: 985.5173
Validation loss improved from 985.5173 to 893.7192 in epoch 22. Saving model...
Validation loss improved from 893.7192 to 850.8436 in epoch 23. Saving model...
Validation loss improved from 850.8436 to 766.4728 in epoch 24. Saving model...
Validation loss improved from 766.4728 to 749.7200 in epoch 25. Saving model...
Validation loss improved from 749.7200 to 735.9858 in epoch 26. Saving model...
Validation loss improved from 735.9858 to 727.5900 in epoch 27. Saving model...
Validation loss improved from 727.5900 to 722.3443 in epoch 28. Saving model...
Validation loss improved from 722.3443 to 718.5862 in epoch 29. Saving model...
Validation loss improved from 718.5862 to 705.1375 in epoch 30. Saving model...
Validation loss improved from 705.1375 to 697.4238 in epoch 31. Saving model...
Epoch 31/5000 - Train Loss: 1957.0989, Val Loss: 697.4238
Validation loss improved from 697.4238 to 692.6115 in epoch 32. Saving model...
Validation loss improved from 692.6115 to 688.8418 in epoch 36. Saving model...
Validation loss improved from 688.8418 to 686.9318 in epoch 37. Saving model...
Validation loss improved from 686.9318 to 684.8981 in epoch 38. Saving model...
Validation loss improved from 684.8981 to 683.6097 in epoch 39. Saving model...
Validation loss improved from 683.6097 to 672.7162 in epoch 40. Saving model...
Epoch 41/5000 - Train Loss: 1945.5706, Val Loss: 675.2853
Validation loss improved from 672.7162 to 668.6349 in epoch 46. Saving model...
Validation loss improved from 668.6349 to 667.8656 in epoch 47. Saving model...
Validation loss improved from 667.8656 to 664.6194 in epoch 48. Saving model...
Validation loss improved from 664.6194 to 659.2737 in epoch 49. Saving model...
Validation loss improved from 659.2737 to 653.0179 in epoch 50. Saving model...
Validation loss improved from 653.0179 to 651.8809 in epoch 51. Saving model...
Epoch 51/5000 - Train Loss: 1937.5992, Val Loss: 651.8809
Validation loss improved from 651.8809 to 640.8004 in epoch 52. Saving model...
Validation loss improved from 640.8004 to 637.0527 in epoch 54. Saving model...
Validation loss improved from 637.0527 to 630.3358 in epoch 55. Saving model...
Validation loss improved from 630.3358 to 629.7595 in epoch 56. Saving model...
Validation loss improved from 629.7595 to 629.2908 in epoch 61. Saving model...
Epoch 61/5000 - Train Loss: 1932.7931, Val Loss: 629.2908
Validation loss improved from 629.2908 to 629.1536 in epoch 62. Saving model...
Epoch 71/5000 - Train Loss: 1922.8561, Val Loss: 665.8350
Epoch 81/5000 - Train Loss: 1912.8736, Val Loss: 679.3547
Epoch 91/5000 - Train Loss: 1901.5518, Val Loss: 668.3197
Validation loss improved from 629.1536 to 595.2377 in epoch 101. Saving model...
Epoch 101/5000 - Train Loss: 1841.7659, Val Loss: 595.2377
Validation loss improved from 595.2377 to 505.9796 in epoch 106. Saving model...
Validation loss improved from 505.9796 to 35.1521 in epoch 107. Saving model...
Validation loss improved from 35.1521 to 30.2131 in epoch 108. Saving model...
Validation loss improved from 30.2131 to 11.4710 in epoch 109. Saving model...
Validation loss improved from 11.4710 to 4.9521 in epoch 110. Saving model...
Validation loss improved from 4.9521 to 4.3546 in epoch 111. Saving model...
Epoch 111/5000 - Train Loss: 1314.5480, Val Loss: 4.3546
Validation loss improved from 4.3546 to 2.7580 in epoch 112. Saving model...
Validation loss improved from 2.7580 to 1.0643 in epoch 113. Saving model...
Validation loss improved from 1.0643 to 0.3727 in epoch 114. Saving model...
Validation loss improved from 0.3727 to 0.1444 in epoch 115. Saving model...
Validation loss improved from 0.1444 to 0.0499 in epoch 116. Saving model...
Validation loss improved from 0.0499 to -0.0064 in epoch 117. Saving model...
Validation loss improved from -0.0064 to -0.0524 in epoch 118. Saving model...
Validation loss improved from -0.0524 to -0.0850 in epoch 119. Saving model...
Validation loss improved from -0.0850 to -0.1121 in epoch 120. Saving model...
Validation loss improved from -0.1121 to -0.1333 in epoch 121. Saving model...
Epoch 121/5000 - Train Loss: 2.8872, Val Loss: -0.1333
Validation loss improved from -0.1333 to -0.1535 in epoch 122. Saving model...
Validation loss improved from -0.1535 to -0.1710 in epoch 123. Saving model...
Validation loss improved from -0.1710 to -0.1880 in epoch 124. Saving model...
Validation loss improved from -0.1880 to -0.2000 in epoch 125. Saving model...
Validation loss improved from -0.2000 to -0.2102 in epoch 126. Saving model...
Validation loss improved from -0.2102 to -0.2184 in epoch 127. Saving model...
Validation loss improved from -0.2184 to -0.2271 in epoch 128. Saving model...
Validation loss improved from -0.2271 to -0.2348 in epoch 129. Saving model...
Validation loss improved from -0.2348 to -0.2424 in epoch 130. Saving model...
Validation loss improved from -0.2424 to -0.2492 in epoch 131. Saving model...
Epoch 131/5000 - Train Loss: 2.5129, Val Loss: -0.2492
Validation loss improved from -0.2492 to -0.2556 in epoch 132. Saving model...
Validation loss improved from -0.2556 to -0.2626 in epoch 133. Saving model...
Validation loss improved from -0.2626 to -0.2724 in epoch 134. Saving model...
Validation loss improved from -0.2724 to -0.2794 in epoch 135. Saving model...
Validation loss improved from -0.2794 to -0.2848 in epoch 136. Saving model...
Validation loss improved from -0.2848 to -0.2892 in epoch 137. Saving model...
Validation loss improved from -0.2892 to -0.2926 in epoch 138. Saving model...
Validation loss improved from -0.2926 to -0.2963 in epoch 139. Saving model...
Validation loss improved from -0.2963 to -0.2997 in epoch 140. Saving model...
Validation loss improved from -0.2997 to -0.3039 in epoch 141. Saving model...
Epoch 141/5000 - Train Loss: 2.2341, Val Loss: -0.3039
Validation loss improved from -0.3039 to -0.3082 in epoch 142. Saving model...
Validation loss improved from -0.3082 to -0.3120 in epoch 143. Saving model...
Validation loss improved from -0.3120 to -0.3149 in epoch 144. Saving model...
Validation loss improved from -0.3149 to -0.3183 in epoch 145. Saving model...
Validation loss improved from -0.3183 to -0.3217 in epoch 146. Saving model...
Validation loss improved from -0.3217 to -0.3245 in epoch 147. Saving model...
Validation loss improved from -0.3245 to -0.3273 in epoch 148. Saving model...
Validation loss improved from -0.3273 to -0.3297 in epoch 149. Saving model...
Validation loss improved from -0.3297 to -0.3320 in epoch 150. Saving model...
Validation loss improved from -0.3320 to -0.3343 in epoch 151. Saving model...
Epoch 151/5000 - Train Loss: 1.9989, Val Loss: -0.3343
Validation loss improved from -0.3343 to -0.3365 in epoch 152. Saving model...
Validation loss improved from -0.3365 to -0.3385 in epoch 153. Saving model...
Validation loss improved from -0.3385 to -0.3411 in epoch 154. Saving model...
Validation loss improved from -0.3411 to -0.3433 in epoch 155. Saving model...
Validation loss improved from -0.3433 to -0.3455 in epoch 156. Saving model...
Validation loss improved from -0.3455 to -0.3481 in epoch 157. Saving model...
Validation loss improved from -0.3481 to -0.3505 in epoch 158. Saving model...
Validation loss improved from -0.3505 to -0.3524 in epoch 159. Saving model...
Validation loss improved from -0.3524 to -0.3543 in epoch 160. Saving model...
Validation loss improved from -0.3543 to -0.3561 in epoch 161. Saving model...
Epoch 161/5000 - Train Loss: 1.7933, Val Loss: -0.3561
Validation loss improved from -0.3561 to -0.3575 in epoch 162. Saving model...
Validation loss improved from -0.3575 to -0.3589 in epoch 163. Saving model...
Validation loss improved from -0.3589 to -0.3600 in epoch 164. Saving model...
Validation loss improved from -0.3600 to -0.3610 in epoch 165. Saving model...
Validation loss improved from -0.3610 to -0.3625 in epoch 166. Saving model...
Validation loss improved from -0.3625 to -0.3641 in epoch 167. Saving model...
Validation loss improved from -0.3641 to -0.3657 in epoch 168. Saving model...
Validation loss improved from -0.3657 to -0.3660 in epoch 169. Saving model...
Validation loss improved from -0.3660 to -0.3722 in epoch 171. Saving model...
Epoch 171/5000 - Train Loss: 1.5115, Val Loss: -0.3722
Validation loss improved from -0.3722 to -0.3768 in epoch 172. Saving model...
Validation loss improved from -0.3768 to -0.3809 in epoch 173. Saving model...
Validation loss improved from -0.3809 to -0.3849 in epoch 174. Saving model...
Validation loss improved from -0.3849 to -0.3878 in epoch 175. Saving model...
Validation loss improved from -0.3878 to -0.3901 in epoch 176. Saving model...
Validation loss improved from -0.3901 to -0.3923 in epoch 177. Saving model...
Validation loss improved from -0.3923 to -0.3943 in epoch 178. Saving model...
Validation loss improved from -0.3943 to -0.3969 in epoch 179. Saving model...
Epoch 181/5000 - Train Loss: 0.1693, Val Loss: -0.3929
Epoch 191/5000 - Train Loss: -0.1446, Val Loss: -0.3882
Epoch 201/5000 - Train Loss: -0.1913, Val Loss: -0.3866
Epoch 211/5000 - Train Loss: -0.2119, Val Loss: -0.3855
Epoch 221/5000 - Train Loss: -0.2252, Val Loss: -0.3851
Epoch 231/5000 - Train Loss: -0.2347, Val Loss: -0.3852
Epoch 241/5000 - Train Loss: -0.2938, Val Loss: -0.3859
Epoch 251/5000 - Train Loss: -0.3072, Val Loss: -0.3865
Epoch 261/5000 - Train Loss: -0.3184, Val Loss: -0.3873
Epoch 271/5000 - Train Loss: -0.3242, Val Loss: -0.3882
Epoch 281/5000 - Train Loss: -0.3604, Val Loss: -0.3882
Epoch 291/5000 - Train Loss: -0.3717, Val Loss: -0.3882
Epoch 301/5000 - Train Loss: -0.3773, Val Loss: -0.3895
Epoch 311/5000 - Train Loss: -0.3818, Val Loss: -0.3900
Epoch 321/5000 - Train Loss: -0.3844, Val Loss: -0.3901
Epoch 331/5000 - Train Loss: -0.3863, Val Loss: -0.3898
Epoch 341/5000 - Train Loss: -0.3876, Val Loss: -0.3897
Epoch 351/5000 - Train Loss: -0.3885, Val Loss: -0.3896
Epoch 361/5000 - Train Loss: -0.3892, Val Loss: -0.3898
Epoch 371/5000 - Train Loss: -0.3898, Val Loss: -0.3894
Epoch 381/5000 - Train Loss: -0.3904, Val Loss: -0.3882
Epoch 391/5000 - Train Loss: -0.3909, Val Loss: -0.3890
Epoch 401/5000 - Train Loss: -0.3912, Val Loss: -0.3891
Epoch 411/5000 - Train Loss: -0.3917, Val Loss: -0.3882
Epoch 421/5000 - Train Loss: -0.3920, Val Loss: -0.3890
Epoch 431/5000 - Train Loss: -0.3923, Val Loss: -0.3896
Epoch 441/5000 - Train Loss: -0.3926, Val Loss: -0.3900
Epoch 451/5000 - Train Loss: -0.3927, Val Loss: -0.3903
Epoch 461/5000 - Train Loss: -0.3929, Val Loss: -0.3900
Epoch 471/5000 - Train Loss: -0.3931, Val Loss: -0.3905
Epoch 481/5000 - Train Loss: -0.3933, Val Loss: -0.3908
Epoch 491/5000 - Train Loss: -0.3935, Val Loss: -0.3914
Epoch 501/5000 - Train Loss: -0.3939, Val Loss: -0.3918
Epoch 511/5000 - Train Loss: -0.3941, Val Loss: -0.3924
Epoch 521/5000 - Train Loss: -0.3943, Val Loss: -0.3914
Epoch 531/5000 - Train Loss: -0.3946, Val Loss: -0.3918
Epoch 541/5000 - Train Loss: -0.3948, Val Loss: -0.3931
Epoch 551/5000 - Train Loss: -0.3951, Val Loss: -0.3931
Epoch 561/5000 - Train Loss: -0.3954, Val Loss: -0.3939
Epoch 571/5000 - Train Loss: -0.3956, Val Loss: -0.3944
Epoch 581/5000 - Train Loss: -0.3958, Val Loss: -0.3950
Epoch 591/5000 - Train Loss: -0.3961, Val Loss: -0.3958
Epoch 601/5000 - Train Loss: -0.3964, Val Loss: -0.3954
Epoch 611/5000 - Train Loss: -0.3967, Val Loss: -0.3959
Epoch 621/5000 - Train Loss: -0.3971, Val Loss: -0.3966
Validation loss improved from -0.3969 to -0.3970 in epoch 622. Saving model...
Validation loss improved from -0.3970 to -0.3972 in epoch 623. Saving model...
Validation loss improved from -0.3972 to -0.3974 in epoch 624. Saving model...
Epoch 631/5000 - Train Loss: -0.3976, Val Loss: -0.3956
Epoch 641/5000 - Train Loss: -0.3976, Val Loss: -0.3965
Epoch 651/5000 - Train Loss: -0.3980, Val Loss: -0.3970
Validation loss improved from -0.3974 to -0.3978 in epoch 660. Saving model...
Validation loss improved from -0.3978 to -0.3980 in epoch 661. Saving model...
Epoch 661/5000 - Train Loss: -0.3985, Val Loss: -0.3980
Validation loss improved from -0.3980 to -0.3981 in epoch 662. Saving model...
Validation loss improved from -0.3981 to -0.3982 in epoch 663. Saving model...
Validation loss improved from -0.3982 to -0.3984 in epoch 664. Saving model...
Validation loss improved from -0.3984 to -0.3984 in epoch 666. Saving model...
Validation loss improved from -0.3984 to -0.3986 in epoch 668. Saving model...
Validation loss improved from -0.3986 to -0.3987 in epoch 669. Saving model...
Validation loss improved from -0.3987 to -0.3989 in epoch 670. Saving model...
Validation loss improved from -0.3989 to -0.3990 in epoch 671. Saving model...
Epoch 671/5000 - Train Loss: -0.3987, Val Loss: -0.3990
Validation loss improved from -0.3990 to -0.3992 in epoch 673. Saving model...
Validation loss improved from -0.3992 to -0.3994 in epoch 677. Saving model...
Validation loss improved from -0.3994 to -0.3997 in epoch 678. Saving model...
Epoch 681/5000 - Train Loss: -0.3992, Val Loss: -0.3992
Epoch 691/5000 - Train Loss: -0.3996, Val Loss: -0.3995
Validation loss improved from -0.3997 to -0.3997 in epoch 696. Saving model...
Validation loss improved from -0.3997 to -0.3999 in epoch 697. Saving model...
Validation loss improved from -0.3999 to -0.4002 in epoch 698. Saving model...
Epoch 701/5000 - Train Loss: -0.4000, Val Loss: -0.3998
Validation loss improved from -0.4002 to -0.4005 in epoch 703. Saving model...
Epoch 711/5000 - Train Loss: -0.4005, Val Loss: -0.3995
Validation loss improved from -0.4005 to -0.4006 in epoch 717. Saving model...
Validation loss improved from -0.4006 to -0.4008 in epoch 719. Saving model...
Validation loss improved from -0.4008 to -0.4009 in epoch 720. Saving model...
Validation loss improved from -0.4009 to -0.4012 in epoch 721. Saving model...
Epoch 721/5000 - Train Loss: -0.4009, Val Loss: -0.4012
Validation loss improved from -0.4012 to -0.4013 in epoch 722. Saving model...
Validation loss improved from -0.4013 to -0.4018 in epoch 723. Saving model...
Validation loss improved from -0.4018 to -0.4018 in epoch 728. Saving model...
Validation loss improved from -0.4018 to -0.4019 in epoch 729. Saving model...
Epoch 731/5000 - Train Loss: -0.4014, Val Loss: -0.4016
Validation loss improved from -0.4019 to -0.4020 in epoch 732. Saving model...
Validation loss improved from -0.4020 to -0.4023 in epoch 733. Saving model...
Validation loss improved from -0.4023 to -0.4024 in epoch 735. Saving model...
Validation loss improved from -0.4024 to -0.4029 in epoch 736. Saving model...
Validation loss improved from -0.4029 to -0.4031 in epoch 737. Saving model...
Validation loss improved from -0.4031 to -0.4035 in epoch 739. Saving model...
Validation loss improved from -0.4035 to -0.4035 in epoch 740. Saving model...
Epoch 741/5000 - Train Loss: -0.4018, Val Loss: -0.4029
Epoch 751/5000 - Train Loss: -0.4025, Val Loss: -0.4031
Validation loss improved from -0.4035 to -0.4036 in epoch 753. Saving model...
Validation loss improved from -0.4036 to -0.4037 in epoch 755. Saving model...
Validation loss improved from -0.4037 to -0.4038 in epoch 756. Saving model...
Validation loss improved from -0.4038 to -0.4041 in epoch 757. Saving model...
Validation loss improved from -0.4041 to -0.4042 in epoch 759. Saving model...
Validation loss improved from -0.4042 to -0.4045 in epoch 761. Saving model...
Epoch 761/5000 - Train Loss: -0.4029, Val Loss: -0.4045
Epoch 771/5000 - Train Loss: -0.4039, Val Loss: -0.4033
Epoch 781/5000 - Train Loss: -0.4042, Val Loss: -0.4043
Validation loss improved from -0.4045 to -0.4047 in epoch 784. Saving model...
Validation loss improved from -0.4047 to -0.4048 in epoch 785. Saving model...
Validation loss improved from -0.4048 to -0.4051 in epoch 787. Saving model...
Validation loss improved from -0.4051 to -0.4053 in epoch 789. Saving model...
Validation loss improved from -0.4053 to -0.4058 in epoch 790. Saving model...
Validation loss improved from -0.4058 to -0.4063 in epoch 791. Saving model...
Epoch 791/5000 - Train Loss: -0.4048, Val Loss: -0.4063
Validation loss improved from -0.4063 to -0.4064 in epoch 792. Saving model...
Validation loss improved from -0.4064 to -0.4066 in epoch 795. Saving model...
Validation loss improved from -0.4066 to -0.4066 in epoch 796. Saving model...
Validation loss improved from -0.4066 to -0.4069 in epoch 797. Saving model...
Validation loss improved from -0.4069 to -0.4070 in epoch 798. Saving model...
Validation loss improved from -0.4070 to -0.4070 in epoch 800. Saving model...
Epoch 801/5000 - Train Loss: -0.4054, Val Loss: -0.4068
Validation loss improved from -0.4070 to -0.4072 in epoch 802. Saving model...
Validation loss improved from -0.4072 to -0.4073 in epoch 804. Saving model...
Validation loss improved from -0.4073 to -0.4079 in epoch 805. Saving model...
Validation loss improved from -0.4079 to -0.4085 in epoch 808. Saving model...
Validation loss improved from -0.4085 to -0.4087 in epoch 809. Saving model...
Epoch 811/5000 - Train Loss: -0.4061, Val Loss: -0.4083
Epoch 821/5000 - Train Loss: -0.4069, Val Loss: -0.4080
Validation loss improved from -0.4087 to -0.4092 in epoch 827. Saving model...
Validation loss improved from -0.4092 to -0.4093 in epoch 829. Saving model...
Validation loss improved from -0.4093 to -0.4094 in epoch 830. Saving model...
Validation loss improved from -0.4094 to -0.4096 in epoch 831. Saving model...
Epoch 831/5000 - Train Loss: -0.4075, Val Loss: -0.4096
Validation loss improved from -0.4096 to -0.4101 in epoch 833. Saving model...
Validation loss improved from -0.4101 to -0.4106 in epoch 839. Saving model...
Validation loss improved from -0.4106 to -0.4107 in epoch 840. Saving model...
Epoch 841/5000 - Train Loss: -0.4082, Val Loss: -0.4107
Validation loss improved from -0.4107 to -0.4108 in epoch 844. Saving model...
Validation loss improved from -0.4108 to -0.4109 in epoch 845. Saving model...

In [4]:
trainer.model

distModel(
  (input_layer): Linear(in_features=3, out_features=50, bias=True)
  (hidden_layers): ModuleList()
  (output_mean_layer): Linear(in_features=50, out_features=1, bias=True)
  (output_sd_layer): Linear(in_features=50, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.05, inplace=False)
)

In [5]:
#trainer.predict(X=trainer.X_test)

In [6]:
trainer.evaluate_gaussian_nll()
trainer.evaluate_standardized_residuals()

Baseline Gaussian NLL Loss: 0.4348
Model Gaussian NLL Loss: -1.1317
KS test against N(0,1): statistic = 0.0732, p-value = 0.2229
✅ The standardized residuals do not significantly differ from a standard normal distribution — model variance estimates appear well-calibrated.
Saved: residual_diagnostics\z_histogram.png
Saved: residual_diagnostics\z_qqplot.png

(np.float64(0.07320890511890416), np.float64(0.22289480793583993))

In [7]:
'''# Inputs
x = np.array([[-1.266313, -0.405118, 0.612491]])

# Extract weights from model
state_dict = trainer.model.state_dict()
w0 = state_dict['input_layer.weight'].cpu().numpy()
b0 = state_dict['input_layer.bias'].cpu().numpy()

w1 = state_dict['hidden_layers.0.weight'].cpu().numpy()
b1 = state_dict['hidden_layers.0.bias'].cpu().numpy()

w_mean = state_dict['output_mean_layer.weight'].cpu().numpy()
b_mean = state_dict['output_mean_layer.bias'].cpu().numpy()

w_sd = state_dict['output_sd_layer.weight'].cpu().numpy()
b_sd = state_dict['output_sd_layer.bias'].cpu().numpy()

# Manual forward pass
def relu(x): return np.maximum(0, x)

h0 = relu(x.dot(w0.T) + b0)
h1 = relu(h0.dot(w1.T) + b1)
mean = h1.dot(w_mean.T) + b_mean
sd = relu(h1.dot(w_sd.T) + b_sd)

print("Manual mean:", mean)
print("Manual std:", sd)'''

'# Inputs\nx = np.array([[-1.266313, -0.405118, 0.612491]])\n\n# Extract weights from model\nstate_dict = trainer.model.state_dict()\nw0 = state_dict[\'input_layer.weight\'].cpu().numpy()\nb0 = state_dict[\'input_layer.bias\'].cpu().numpy()\n\nw1 = state_dict[\'hidden_layers.0.weight\'].cpu().numpy()\nb1 = state_dict[\'hidden_layers.0.bias\'].cpu().numpy()\n\nw_mean = state_dict[\'output_mean_layer.weight\'].cpu().numpy()\nb_mean = state_dict[\'output_mean_layer.bias\'].cpu().numpy()\n\nw_sd = state_dict[\'output_sd_layer.weight\'].cpu().numpy()\nb_sd = state_dict[\'output_sd_layer.bias\'].cpu().numpy()\n\n# Manual forward pass\ndef relu(x): return np.maximum(0, x)\n\nh0 = relu(x.dot(w0.T) + b0)\nh1 = relu(h0.dot(w1.T) + b1)\nmean = h1.dot(w_mean.T) + b_mean\nsd = relu(h1.dot(w_sd.T) + b_sd)\n\nprint("Manual mean:", mean)\nprint("Manual std:", sd)'

In [8]:
cons = trainer.constraint_build()
cons.to_csv('constraints.csv')

In [9]:
cons = pd.read_csv('constraints.csv', index_col=0)
pd.set_option('display.precision', 10)
cons

,intercept,layer,node,node_0,node_1,node_2,node_3,node_4,node_5,node_6,...,node_40,node_41,node_42,node_43,node_44,node_45,node_46,node_47,node_48,node_49
0,-0.2141019700,0,0,0.296281640,-0.2567882500,-0.1232720500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.7054593000,0,1,0.207522020,-0.3485039000,0.3076981000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.1057791860,0,2,-0.054186980,0.3172796400,0.0428181500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.3189473700,0,3,-0.119734940,0.0983284800,0.0407778620,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.1962385500,0,4,0.117487700,0.1009395600,-0.7765464000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-0.3715920000,0,5,-0.051977277,0.0836834300,-0.0023064017,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,-0.3013923800,0,6,0.544596400,0.1449148200,-0.2017014600,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-0.8214972000,0,7,-0.263572160,-0.1033989040,-0.9038853000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.7377847000,0,8,-0.213908420,0.0935788100,0.2366237800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,-0.1321359600,0,9,0.355235640,-0.5896207700,0.3651097400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,-0.3583759000,0,10,0.209056360,0.5294191000,0.3364107300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.1922294300,0,11,-0.466360870,-0.5581668000,-0.2522150000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0.2386093100,0,12,0.468055100,-0.1042522640,0.2450927500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.4221018000,0,13,-0.277027500,0.5627405600,-0.2876220000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,-0.3303291500,0,14,0.398742940,0.0149951170,-0.3290515800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.1575779300,0,15,0.298121900,-0.3393080200,0.1175799200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-0.2182542100,0,16,-0.149649590,-0.0229782800,-0.5649637600,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,-0.1197000700,0,17,-0.244347320,0.3497255700,-0.0931875000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,-0.5404678000,0,18,0.511793900,0.4200837300,-0.0223672430,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,-0.2295938900,0,19,-0.426733700,0.1300489300,0.0991865800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0.2696752500,0,20,-0.132571380,0.4372539000,0.4615001700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.2971630700,0,21,0.536057200,-0.3431908000,-0.1406818500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.1767526000,0,22,-0.018703878,0.0301861840,-0.4372812800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.1357029500,0,23,-0.412277300,0.2905199000,-0.0692982300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.5322879600,0,24,0.270391550,0.0445506900,0.1748609700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0.5275561000,0,25,0.085291420,0.1906035200,0.3063063600,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0.5188274400,0,26,-0.552367800,0.3066646500,-0.3019278300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,-0.0924683700,0,27,-0.469278500,0.0047503705,-0.0285144840,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,-0.3227974000,0,28,0.384066550,-0.3068806200,-0.5973578000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.4268160800,0,29,0.419125700,-0.0438392870,0.3173993200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,-0.1604898700,0,30,0.157224210,-0.5052625500,0.1091100400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,-0.0609564740,0,31,0.152088340,-0.3780304500,-0.2911143300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,-0.4244724500,0,32,0.252037730,0.1853584500,-0.2913718000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,-0.1765022100,0,33,-0.165102820,0.4960582600,-0.0560660250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,-0.4097900700,0,34,0.273798320,0.2086070600,-0.3697010300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0.5070567000,0,35,-0.454060260,0.5649392600,0.0416468800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,-0.5274946700,0,36,0.369945730,0.1943311000,0.1828343700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,-0.4489548500,0,37,0.197717900,0.5534774000,-0.6883049600,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,-0.0130461590,0,38,0.168943480,0.3637346600,0.3895971000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-0.3262512400,0,39,0.328559640,-0.4676024300,-0.3922156700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.2771477400,0,40,-0.287905070,0.2336737700,0.5461053000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-0.2549131000,0,41,-0.304812370,0.3171480300,-0.3246307000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,-0.3130214000,0,42,-0.402565200,-0.3290678000,0.2691728500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,0.0211447720,0,43,0.529392900,-0.3429675000,0.0824963300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,0.3791747400,0,44,0.461460080,0.3802133500,0.3701493000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,-0.4291255800,0,45,0.385598200,0.3688280600,0.1523665000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,0.5709916400,0,46,-0.105810545,-0.6653651600,-0.1179522700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0.3516471700,0,47,-0.094004210,-0.2356639700,0.2139390400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,0.5221945000,0,48,0.131758990,-0.1273830700,0.2451123400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,-0.1939122700,0,49,-0.115358940,0.3243507400,0.6297203300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0.0547893870,1,0,0.197379890,-0.1271459800,0.1195466150,-0.11361786,1.244779500,0.004210323,0.069214374,...,-0.112606230,0.138208420,0.142265410,-0.0530300180,-0.15386869,0.084260820,-0.219175370,-0.106330425,-0.147133050,0.18644537
0,0.0019231059,2,0,0.042770530,0.0638919300,0.0836086800,0.20915067,-0.061708264,0.081563130,0.107353670,...,-0.030760024,0.040634543,0.041369535,0.0032912276,-0.05074508,-0.023872172,0.038980164,-0.009029015,-0.027699322,-0.25342506

In [10]:
n_sc =  30
#contextual_var = trainer.X_test
contextual_var = trainer.X_test.iloc[[0]]
contextual_var.reset_index(drop=True, inplace=True)
contextual_var

             x1            x2         price
0  0.1317971241  0.4232970643 -0.6373367167

In [11]:
contextual_var.columns.sort_values()

Index(['price', 'x1', 'x2'], dtype='object')

In [12]:
row = pd.DataFrame([{
    'x1': -1.266313,
    'x2': -0.405118,
    'price': 30.0
}])

def preict_one_row(row):
    # Predict
    mean_pred, sd_pred = trainer.predict(row, unscale=True)
    print("Mean prediction:", mean_pred)
    print("Standard deviation prediction:", sd_pred)

preict_one_row(row)

Mean prediction: [[-14.73813958]]
Standard deviation prediction: [[0.]]

In [13]:
model = pyo.ConcreteModel()

model.N = pyo.RangeSet(0,n_preds-1)
model.W = pyo.RangeSet(1,n_sc) # scenarios

pi = [1/n_sc for i in range(n_sc)]

model.var_ind = pyo.Set(initialize=contextual_var.columns.sort_values())

model.x = pyo.Var(model.var_ind, model.N) # price

model.y = pyo.Var(pyo.Any, dense=False, domain=pyo.Reals)

model.rent = pyo.Var(model.W, within=pyo.Reals) # rentabilidad per scenario

#definition of the objective function
def obj_expression(model):
    return sum(pi[w-1] * model.rent[w] for w in model.W)
model.OBJ = pyo.Objective(rule=obj_expression, sense=pyo.maximize)

#definition of the constraints
def rent_expression(model, w):
    return model.rent[w] == sum(model.y['demand', n, w]*model.x['price',n] for n in model.N)
model.rent_expression = pyo.Constraint(model.W, rule=rent_expression)

#constraint for fixing contextual information
def const9_rule(model,x_ind,n):
    if x_ind=='price':
        return pyo.Constraint.Skip
    else:
        return model.x[x_ind,n] == contextual_var.loc[n,x_ind]
model.const9 = pyo.Constraint(model.var_ind, model.N, rule=const9_rule)

P_max = 30
# max price constraint for each price
def max_price_expression(model, n):
    return model.x['price', n] <= P_max

model.max_price_expression = pyo.Constraint(model.N, rule=max_price_expression)

def min_price_expression(model, n):
    return model.x['price', n] >= 0
model.min_price_expression = pyo.Constraint(model.N, rule=min_price_expression)

In [14]:
const_embed(model=trainer, opt_model=model, constaints=cons, outcome='demand', n_scenarios=n_sc)

In [15]:
opt = pyo.SolverFactory('gurobi_direct')
opt.options['threads'] = 0
opt.options['NonConvex'] = 2
results = opt.solve(model, tee=True)

Set parameter OutputFlag to value 1
Set parameter Threads to value 0
Set parameter NonConvex to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i5-13500, instruction set [SSE2|AVX|AVX2]
Thread count: 14 physical cores, 20 logical processors, using up to 20 threads

Non-default parameters:
NonConvex  2

Optimize a model with 186 rows, 165 columns and 746 nonzeros
Model fingerprint: 0x1d719707
Model has 30 quadratic constraints
Variable types: 115 continuous, 50 integer (50 binary)
Coefficient statistics:
  Matrix range     [4e-04, 1e+03]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [3e-02, 3e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e-03, 1e+03]
Presolve removed 58 rows and 68 columns
Presolve time: 0.01s
Presolved: 189 rows, 129 columns, 563 nonzeros
Presolved model has 30 bilinear constraint(s)

Solving non-convex MIQCP

Variable types: 97 continuous, 32 integer (32 binary)
Found heuristic solution: objective 38.0809561

Root relaxation: objective 3.057620e+02, 112 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  305.76196    0   47   38.08096  305.76196   703%     -    0s
     0     0  227.15290    0   56   38.08096  227.15290   497%     -    0s
     0     0  189.56678    0   52   38.08096  189.56678   398%     -    0s
H    0     0                      49.5957928  184.99705   273%     -    0s
     0     0   50.28337    0   48   49.59579   50.28337  1.39%     -    0s

Cutting planes:
  Gomory: 3
  Cover: 19
  Implied bound: 30
  Clique: 14
  MIR: 26
  Flow cover: 22
  RLT: 97
  Relax-and-lift: 7
  BQP: 25
  PSD: 1

Explored 1 nodes (358 simplex iterations) in 0.08 seconds (0.05 work units)
Thread count was 20 (of 20 available processors)

Solution count 2: 49.5958 38.081

Optimal solution found (tolerance 1.00e-04)
Best objective 4.959579283840e+01, best bound 4.959982255389e+01, gap 0.0081%

In [16]:
for c in model.component_objects(Constraint, active=True):
    print(f"Constraint component: {c.name}")
    for index in c:
        print(f"  {index}: {c[index].expr}")

Constraint component: rent_expression
  1: rent[1]  ==  y[demand,0,1]*x[price,0]
  2: rent[2]  ==  y[demand,0,2]*x[price,0]
  3: rent[3]  ==  y[demand,0,3]*x[price,0]
  4: rent[4]  ==  y[demand,0,4]*x[price,0]
  5: rent[5]  ==  y[demand,0,5]*x[price,0]
  6: rent[6]  ==  y[demand,0,6]*x[price,0]
  7: rent[7]  ==  y[demand,0,7]*x[price,0]
  8: rent[8]  ==  y[demand,0,8]*x[price,0]
  9: rent[9]  ==  y[demand,0,9]*x[price,0]
  10: rent[10]  ==  y[demand,0,10]*x[price,0]
  11: rent[11]  ==  y[demand,0,11]*x[price,0]
  12: rent[12]  ==  y[demand,0,12]*x[price,0]
  13: rent[13]  ==  y[demand,0,13]*x[price,0]
  14: rent[14]  ==  y[demand,0,14]*x[price,0]
  15: rent[15]  ==  y[demand,0,15]*x[price,0]
  16: rent[16]  ==  y[demand,0,16]*x[price,0]
  17: rent[17]  ==  y[demand,0,17]*x[price,0]
  18: rent[18]  ==  y[demand,0,18]*x[price,0]
  19: rent[19]  ==  y[demand,0,19]*x[price,0]
  20: rent[20]  ==  y[demand,0,20]*x[price,0]
  21: rent[21]  ==  y[demand,0,21]*x[price,0]
  22: rent[22]  ==  y[demand,0,22]*x[price,0]
  23: rent[23]  ==  y[demand,0,23]*x[price,0]
  24: rent[24]  ==  y[demand,0,24]*x[price,0]
  25: rent[25]  ==  y[demand,0,25]*x[price,0]
  26: rent[26]  ==  y[demand,0,26]*x[price,0]
  27: rent[27]  ==  y[demand,0,27]*x[price,0]
  28: rent[28]  ==  y[demand,0,28]*x[price,0]
  29: rent[29]  ==  y[demand,0,29]*x[price,0]
  30: rent[30]  ==  y[demand,0,30]*x[price,0]
Constraint component: const9
  ('x1', 0): x[x1,0]  ==  0.1317971240558705
  ('x2', 0): x[x2,0]  ==  0.42329706434473297
Constraint component: max_price_expression
  0: x[price,0]  <=  30
Constraint component: min_price_expression
  0: 0  <=  x[price,0]
Constraint component: constraint_1_layer0_node0_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.29628164 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.25678825 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.12327205 - 0.21410197  <=  v[demand,0,0,0]
Constraint component: constraint_2_layer0_node0_pred0demand
  None: v[demand,0,0,0]  <=  1000.0*v_ind[demand,0,0,0]
Constraint component: constraint_3_layer0_node0_pred0demand
  None: v[demand,0,0,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.29628164 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.25678825 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.12327205 - 0.21410197 + 1000.0*(1 - v_ind[demand,0,0,0])
Constraint component: constraint_1_layer0_node1_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.20752202 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.3485039 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.3076981 + 0.7054593  <=  v[demand,0,1,0]
Constraint component: constraint_2_layer0_node1_pred0demand
  None: v[demand,0,1,0]  <=  1000.0*v_ind[demand,0,1,0]
Constraint component: constraint_3_layer0_node1_pred0demand
  None: v[demand,0,1,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.20752202 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.3485039 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.3076981 + 0.7054593 + 1000.0*(1 - v_ind[demand,0,1,0])
Constraint component: constraint_1_layer0_node2_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.05418698 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.31727964 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.04281815 - 0.105779186  <=  v[demand,0,2,0]
Constraint component: constraint_2_layer0_node2_pred0demand
  None: v[demand,0,2,0]  <=  1000.0*v_ind[demand,0,2,0]
Constraint component: constraint_3_layer0_node2_pred0demand
  None: v[demand,0,2,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.05418698 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.31727964 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.04281815 - 0.105779186 + 1000.0*(1 - v_ind[demand,0,2,0])
Constraint component: constraint_1_layer0_node3_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.11973494 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.09832848 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.040777862 + 0.31894737  <=  v[demand,0,3,0]
Constraint component: constraint_2_layer0_node3_pred0demand
  None: v[demand,0,3,0]  <=  1000.0*v_ind[demand,0,3,0]
Constraint component: constraint_3_layer0_node3_pred0demand
  None: v[demand,0,3,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.11973494 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.09832848 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.040777862 + 0.31894737 + 1000.0*(1 - v_ind[demand,0,3,0])
Constraint component: constraint_1_layer0_node4_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.1174877 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.10093956 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.7765464 + 0.19623855  <=  v[demand,0,4,0]
Constraint component: constraint_2_layer0_node4_pred0demand
  None: v[demand,0,4,0]  <=  1000.0*v_ind[demand,0,4,0]
Constraint component: constraint_3_layer0_node4_pred0demand
  None: v[demand,0,4,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.1174877 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.10093956 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.7765464 + 0.19623855 + 1000.0*(1 - v_ind[demand,0,4,0])
Constraint component: constraint_1_layer0_node5_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.051977277 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.08368343 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.0023064017 - 0.371592  <=  v[demand,0,5,0]
Constraint component: constraint_2_layer0_node5_pred0demand
  None: v[demand,0,5,0]  <=  1000.0*v_ind[demand,0,5,0]
Constraint component: constraint_3_layer0_node5_pred0demand
  None: v[demand,0,5,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.051977277 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.08368343 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.0023064017 - 0.371592 + 1000.0*(1 - v_ind[demand,0,5,0])
Constraint component: constraint_1_layer0_node6_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5445964 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.14491482 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.20170146 - 0.30139238  <=  v[demand,0,6,0]
Constraint component: constraint_2_layer0_node6_pred0demand
  None: v[demand,0,6,0]  <=  1000.0*v_ind[demand,0,6,0]
Constraint component: constraint_3_layer0_node6_pred0demand
  None: v[demand,0,6,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5445964 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.14491482 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.20170146 - 0.30139238 + 1000.0*(1 - v_ind[demand,0,6,0])
Constraint component: constraint_1_layer0_node7_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.26357216 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.103398904 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.9038853 - 0.8214972  <=  v[demand,0,7,0]
Constraint component: constraint_2_layer0_node7_pred0demand
  None: v[demand,0,7,0]  <=  1000.0*v_ind[demand,0,7,0]
Constraint component: constraint_3_layer0_node7_pred0demand
  None: v[demand,0,7,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.26357216 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.103398904 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.9038853 - 0.8214972 + 1000.0*(1 - v_ind[demand,0,7,0])
Constraint component: constraint_1_layer0_node8_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.21390842 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.09357881 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.23662378 + 0.7377847  <=  v[demand,0,8,0]
Constraint component: constraint_2_layer0_node8_pred0demand
  None: v[demand,0,8,0]  <=  1000.0*v_ind[demand,0,8,0]
Constraint component: constraint_3_layer0_node8_pred0demand
  None: v[demand,0,8,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.21390842 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.09357881 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.23662378 + 0.7377847 + 1000.0*(1 - v_ind[demand,0,8,0])
Constraint component: constraint_1_layer0_node9_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.35523564 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.58962077 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.36510974 - 0.13213596  <=  v[demand,0,9,0]
Constraint component: constraint_2_layer0_node9_pred0demand
  None: v[demand,0,9,0]  <=  1000.0*v_ind[demand,0,9,0]
Constraint component: constraint_3_layer0_node9_pred0demand
  None: v[demand,0,9,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.35523564 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.58962077 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.36510974 - 0.13213596 + 1000.0*(1 - v_ind[demand,0,9,0])
Constraint component: constraint_1_layer0_node10_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.20905636 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.5294191 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.33641073 - 0.3583759  <=  v[demand,0,10,0]
Constraint component: constraint_2_layer0_node10_pred0demand
  None: v[demand,0,10,0]  <=  1000.0*v_ind[demand,0,10,0]
Constraint component: constraint_3_layer0_node10_pred0demand
  None: v[demand,0,10,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.20905636 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.5294191 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.33641073 - 0.3583759 + 1000.0*(1 - v_ind[demand,0,10,0])
Constraint component: constraint_1_layer0_node11_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.46636087 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.5581668 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.252215 + 0.19222943  <=  v[demand,0,11,0]
Constraint component: constraint_2_layer0_node11_pred0demand
  None: v[demand,0,11,0]  <=  1000.0*v_ind[demand,0,11,0]
Constraint component: constraint_3_layer0_node11_pred0demand
  None: v[demand,0,11,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.46636087 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.5581668 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.252215 + 0.19222943 + 1000.0*(1 - v_ind[demand,0,11,0])
Constraint component: constraint_1_layer0_node12_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.4680551 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.104252264 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.24509275 + 0.23860931  <=  v[demand,0,12,0]
Constraint component: constraint_2_layer0_node12_pred0demand
  None: v[demand,0,12,0]  <=  1000.0*v_ind[demand,0,12,0]
Constraint component: constraint_3_layer0_node12_pred0demand
  None: v[demand,0,12,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.4680551 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.104252264 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.24509275 + 0.23860931 + 1000.0*(1 - v_ind[demand,0,12,0])
Constraint component: constraint_1_layer0_node13_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.2770275 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.56274056 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.287622 + 0.4221018  <=  v[demand,0,13,0]
Constraint component: constraint_2_layer0_node13_pred0demand
  None: v[demand,0,13,0]  <=  1000.0*v_ind[demand,0,13,0]
Constraint component: constraint_3_layer0_node13_pred0demand
  None: v[demand,0,13,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.2770275 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.56274056 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.287622 + 0.4221018 + 1000.0*(1 - v_ind[demand,0,13,0])
Constraint component: constraint_1_layer0_node14_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.39874294 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.014995117 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.32905158 - 0.33032915  <=  v[demand,0,14,0]
Constraint component: constraint_2_layer0_node14_pred0demand
  None: v[demand,0,14,0]  <=  1000.0*v_ind[demand,0,14,0]
Constraint component: constraint_3_layer0_node14_pred0demand
  None: v[demand,0,14,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.39874294 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.014995117 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.32905158 - 0.33032915 + 1000.0*(1 - v_ind[demand,0,14,0])
Constraint component: constraint_1_layer0_node15_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2981219 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.33930802 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.11757992 + 0.15757793  <=  v[demand,0,15,0]
Constraint component: constraint_2_layer0_node15_pred0demand
  None: v[demand,0,15,0]  <=  1000.0*v_ind[demand,0,15,0]
Constraint component: constraint_3_layer0_node15_pred0demand
  None: v[demand,0,15,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2981219 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.33930802 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.11757992 + 0.15757793 + 1000.0*(1 - v_ind[demand,0,15,0])
Constraint component: constraint_1_layer0_node16_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.14964959 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.02297828 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.56496376 - 0.21825421  <=  v[demand,0,16,0]
Constraint component: constraint_2_layer0_node16_pred0demand
  None: v[demand,0,16,0]  <=  1000.0*v_ind[demand,0,16,0]
Constraint component: constraint_3_layer0_node16_pred0demand
  None: v[demand,0,16,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.14964959 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.02297828 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.56496376 - 0.21825421 + 1000.0*(1 - v_ind[demand,0,16,0])
Constraint component: constraint_1_layer0_node17_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.24434732 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.34972557 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.0931875 - 0.11970007  <=  v[demand,0,17,0]
Constraint component: constraint_2_layer0_node17_pred0demand
  None: v[demand,0,17,0]  <=  1000.0*v_ind[demand,0,17,0]
Constraint component: constraint_3_layer0_node17_pred0demand
  None: v[demand,0,17,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.24434732 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.34972557 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.0931875 - 0.11970007 + 1000.0*(1 - v_ind[demand,0,17,0])
Constraint component: constraint_1_layer0_node18_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5117939 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.42008373 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.022367243 - 0.5404678  <=  v[demand,0,18,0]
Constraint component: constraint_2_layer0_node18_pred0demand
  None: v[demand,0,18,0]  <=  1000.0*v_ind[demand,0,18,0]
Constraint component: constraint_3_layer0_node18_pred0demand
  None: v[demand,0,18,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5117939 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.42008373 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.022367243 - 0.5404678 + 1000.0*(1 - v_ind[demand,0,18,0])
Constraint component: constraint_1_layer0_node19_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.4267337 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.13004893 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.09918658 - 0.22959389  <=  v[demand,0,19,0]
Constraint component: constraint_2_layer0_node19_pred0demand
  None: v[demand,0,19,0]  <=  1000.0*v_ind[demand,0,19,0]
Constraint component: constraint_3_layer0_node19_pred0demand
  None: v[demand,0,19,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.4267337 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.13004893 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.09918658 - 0.22959389 + 1000.0*(1 - v_ind[demand,0,19,0])
Constraint component: constraint_1_layer0_node20_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.13257138 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.4372539 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.46150017 + 0.26967525  <=  v[demand,0,20,0]
Constraint component: constraint_2_layer0_node20_pred0demand
  None: v[demand,0,20,0]  <=  1000.0*v_ind[demand,0,20,0]
Constraint component: constraint_3_layer0_node20_pred0demand
  None: v[demand,0,20,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.13257138 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.4372539 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.46150017 + 0.26967525 + 1000.0*(1 - v_ind[demand,0,20,0])
Constraint component: constraint_1_layer0_node21_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5360572 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.3431908 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.14068185 + 0.29716307  <=  v[demand,0,21,0]
Constraint component: constraint_2_layer0_node21_pred0demand
  None: v[demand,0,21,0]  <=  1000.0*v_ind[demand,0,21,0]
Constraint component: constraint_3_layer0_node21_pred0demand
  None: v[demand,0,21,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.5360572 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.3431908 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.14068185 + 0.29716307 + 1000.0*(1 - v_ind[demand,0,21,0])
Constraint component: constraint_1_layer0_node22_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.018703878 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.030186184 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.43728128 + 0.1767526  <=  v[demand,0,22,0]
Constraint component: constraint_2_layer0_node22_pred0demand
  None: v[demand,0,22,0]  <=  1000.0*v_ind[demand,0,22,0]
Constraint component: constraint_3_layer0_node22_pred0demand
  None: v[demand,0,22,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.018703878 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.030186184 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.43728128 + 0.1767526 + 1000.0*(1 - v_ind[demand,0,22,0])
Constraint component: constraint_1_layer0_node23_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.4122773 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.2905199 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.06929823 + 0.13570295  <=  v[demand,0,23,0]
Constraint component: constraint_2_layer0_node23_pred0demand
  None: v[demand,0,23,0]  <=  1000.0*v_ind[demand,0,23,0]
Constraint component: constraint_3_layer0_node23_pred0demand
  None: v[demand,0,23,0]  <=  (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.4122773 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.2905199 + (x[price,0] - 20.1146255836938)/5.775951226575475*-0.06929823 + 0.13570295 + 1000.0*(1 - v_ind[demand,0,23,0])
Constraint component: constraint_1_layer0_node24_pred0demand
  None: (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.27039155 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.04455069 + (x[price,0] - 20.1146255836938)/5.775951226575475*0.17486097 + 0.53228796  <=  v[demand,0,24,0]
Constraint component: constraint_2_layer0_node24_pred0demand
  None: v[demand,0,24,0]  <=  1000.0*v_ind[demand,0,24,0]
Constraint component: constraint_3_layer0_node24_pred0demand

In [17]:
value(model.x['price', 0])

17.20544914751156

In [18]:
value(model.y['demand', 0, 1])

4.073265370946168

In [19]:
print(value(model.y['demand', 0, 'mean']))
print(value(model.y['demand', 0, 'sd']))

-0.14326587954820888
0.29234956641930726

In [20]:
opt_profit = value(model.OBJ)
print(f"Optimal profit: {opt_profit}")

Optimal profit: 49.59579283840131

In [21]:
opt_price = value(model.x['price',0])
opt_mean = value(model.y['demand', 0,'mean'])
opt_sd = value(model.y['demand', 0,'sd'])

print(f"Optimal price: {opt_price}")
print(f"Optimal mean: {opt_mean}")
print(f"Optimal sd: {opt_sd}")

Optimal price: 17.20544914751156
Optimal mean: -0.14326587954820888
Optimal sd: 0.29234956641930726