In [25]:
import random
random.seed(42)

import torch

import numpy as np
import pyomo.environ as pyo
import pandas as pd
import matplotlib.pyplot as plt

from pyomo.environ import *
from utils import generate_simple_synthetic_data, const_embed, load_case_study_data
from trainer import Trainer

np.random.seed(43)

LOAD_CASE_STUDY = False

In [26]:
if not LOAD_CASE_STUDY:
    X, y, true_mean, true_std = generate_simple_synthetic_data(n_samples=1000)

    print(X.head())
    print(y.head())
else:
    print("Loading case study data...")
    X, y, val_ind, test_ind = load_case_study_data()

             x1            x2          price
0  0.3745401188  0.1851329288  15.2341136747
1  0.9507143064  0.5419009474  14.9395759814
2  0.7319939418  0.8729458359  28.1250916104
3  0.5986584842  0.7322248864  14.9909239970
4  0.1560186404  0.8065611479  15.4389945226
0    4.1641150818
1    9.1615406641
2    0.4333924942
3    5.6618455395
4    5.2185912388
Name: y, dtype: float64

In [27]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

'''model_config = {
    'hidden_layers': 1,
    'hidden_size': 5,
    'drop': 0.2
    }

training_config = {
    'lr': 0.01,
    'wd': 0.0001,
    'batchsize': 64,
    'iters': 500,
    'patience': 20
    }'''

config = {
    # Model config
    'hidden_layers': 0,
    'hidden_size': 50,
    'drop': 0.05,

    # Training config
    'lr': 0.001,
    'wd': 0,
    'batchsize': 64,
    'iters': 5000,
    'patience': 500
}

trainer = Trainer(X, y, config, device=device)

if LOAD_CASE_STUDY:
    trainer.set_data_partitions(X_train=X[(~X.index.isin(val_ind)) & (~X.index.isin(test_ind))], y_train=y[(~y.index.isin(val_ind)) & (~y.index.isin(test_ind))], X_val=X[X.index.isin(val_ind)], y_val=y[y.index.isin(val_ind)], X_test=X[X.index.isin(test_ind)], y_test=y[y.index.isin(test_ind)])
else:
    trainer.create_data_partitions(val_size=0.2, test_size=0.2, random_state=42)

print("X_train shape: ", trainer.X_train.shape)
print("X_val shape: ", trainer.X_val.shape)
print("X_test shape: ", trainer.X_test.shape)

trainer.train()

trainer.test()

X_train shape:  (600, 3)
X_val shape:  (200, 3)
X_test shape:  (200, 3)
Validation loss improved from inf to 9821.1572 in epoch 1. Saving model...
Epoch 1/5000 - Train Loss: 61346.1048, Val Loss: 9821.1572
Validation loss improved from 9821.1572 to 8.4246 in epoch 2. Saving model...
Validation loss improved from 8.4246 to 4.4977 in epoch 3. Saving model...
Validation loss improved from 4.4977 to 3.7120 in epoch 4. Saving model...
Validation loss improved from 3.7120 to 3.4550 in epoch 5. Saving model...
Validation loss improved from 3.4550 to 3.3576 in epoch 6. Saving model...
Validation loss improved from 3.3576 to 3.3149 in epoch 7. Saving model...
Validation loss improved from 3.3149 to 3.2922 in epoch 8. Saving model...
Validation loss improved from 3.2922 to 3.2762 in epoch 9. Saving model...
Validation loss improved from 3.2762 to 3.2606 in epoch 10. Saving model...
Validation loss improved from 3.2606 to 3.2431 in epoch 11. Saving model...
Epoch 11/5000 - Train Loss: 4.0048, Val Loss: 3.2431
Validation loss improved from 3.2431 to 3.2241 in epoch 12. Saving model...
Validation loss improved from 3.2241 to 3.2007 in epoch 13. Saving model...
Validation loss improved from 3.2007 to 3.1649 in epoch 14. Saving model...
Validation loss improved from 3.1649 to 3.1256 in epoch 15. Saving model...
Validation loss improved from 3.1256 to 3.0873 in epoch 16. Saving model...
Validation loss improved from 3.0873 to 3.0375 in epoch 17. Saving model...
Validation loss improved from 3.0375 to 2.9916 in epoch 18. Saving model...
Validation loss improved from 2.9916 to 2.9514 in epoch 19. Saving model...
Validation loss improved from 2.9514 to 2.9157 in epoch 20. Saving model...
Validation loss improved from 2.9157 to 2.8850 in epoch 21. Saving model...
Epoch 21/5000 - Train Loss: 3.5707, Val Loss: 2.8850
Validation loss improved from 2.8850 to 2.8564 in epoch 22. Saving model...
Validation loss improved from 2.8564 to 2.8221 in epoch 23. Saving model...
Validation loss improved from 2.8221 to 2.7890 in epoch 24. Saving model...
Validation loss improved from 2.7890 to 2.7607 in epoch 25. Saving model...
Validation loss improved from 2.7607 to 2.7330 in epoch 26. Saving model...
Validation loss improved from 2.7330 to 2.7065 in epoch 27. Saving model...
Validation loss improved from 2.7065 to 2.6818 in epoch 28. Saving model...
Validation loss improved from 2.6818 to 2.6588 in epoch 29. Saving model...
Validation loss improved from 2.6588 to 2.6367 in epoch 30. Saving model...
Validation loss improved from 2.6367 to 2.6152 in epoch 31. Saving model...
Epoch 31/5000 - Train Loss: 3.3044, Val Loss: 2.6152
Validation loss improved from 2.6152 to 2.5934 in epoch 32. Saving model...
Validation loss improved from 2.5934 to 2.5741 in epoch 33. Saving model...
Validation loss improved from 2.5741 to 2.5545 in epoch 34. Saving model...
Validation loss improved from 2.5545 to 2.5371 in epoch 35. Saving model...
Validation loss improved from 2.5371 to 2.5198 in epoch 36. Saving model...
Validation loss improved from 2.5198 to 2.5026 in epoch 37. Saving model...
Validation loss improved from 2.5026 to 2.4868 in epoch 38. Saving model...
Validation loss improved from 2.4868 to 2.4708 in epoch 39. Saving model...
Validation loss improved from 2.4708 to 2.4521 in epoch 40. Saving model...
Validation loss improved from 2.4521 to 2.4320 in epoch 41. Saving model...
Epoch 41/5000 - Train Loss: 3.0255, Val Loss: 2.4320
Validation loss improved from 2.4320 to 2.4117 in epoch 42. Saving model...
Validation loss improved from 2.4117 to 2.3863 in epoch 43. Saving model...
Validation loss improved from 2.3863 to 2.3482 in epoch 44. Saving model...
Validation loss improved from 2.3482 to 2.2945 in epoch 45. Saving model...
Validation loss improved from 2.2945 to 2.2420 in epoch 46. Saving model...
Validation loss improved from 2.2420 to 2.1967 in epoch 47. Saving model...
Validation loss improved from 2.1967 to 2.1518 in epoch 48. Saving model...
Validation loss improved from 2.1518 to 2.1085 in epoch 49. Saving model...
Validation loss improved from 2.1085 to 2.0666 in epoch 50. Saving model...
Validation loss improved from 2.0666 to 2.0293 in epoch 51. Saving model...
Epoch 51/5000 - Train Loss: 2.5468, Val Loss: 2.0293
Validation loss improved from 2.0293 to 1.9330 in epoch 52. Saving model...
Validation loss improved from 1.9330 to 1.7691 in epoch 53. Saving model...
Validation loss improved from 1.7691 to 1.6020 in epoch 54. Saving model...
Validation loss improved from 1.6020 to 1.4711 in epoch 55. Saving model...
Validation loss improved from 1.4711 to 1.3003 in epoch 56. Saving model...
Validation loss improved from 1.3003 to 1.0923 in epoch 57. Saving model...
Validation loss improved from 1.0923 to 0.8699 in epoch 58. Saving model...
Validation loss improved from 0.8699 to 0.6106 in epoch 59. Saving model...
Validation loss improved from 0.6106 to 0.4073 in epoch 60. Saving model...
Validation loss improved from 0.4073 to 0.2475 in epoch 61. Saving model...
Epoch 61/5000 - Train Loss: 0.8025, Val Loss: 0.2475
Validation loss improved from 0.2475 to 0.1398 in epoch 62. Saving model...
Validation loss improved from 0.1398 to 0.0710 in epoch 63. Saving model...
Validation loss improved from 0.0710 to 0.0138 in epoch 64. Saving model...
Validation loss improved from 0.0138 to -0.0258 in epoch 65. Saving model...
Validation loss improved from -0.0258 to -0.0587 in epoch 66. Saving model...
Validation loss improved from -0.0587 to -0.0951 in epoch 67. Saving model...
Validation loss improved from -0.0951 to -0.1033 in epoch 68. Saving model...
Validation loss improved from -0.1033 to -0.1042 in epoch 69. Saving model...
Epoch 71/5000 - Train Loss: 0.1584, Val Loss: -0.0217
Epoch 81/5000 - Train Loss: 0.1053, Val Loss: -0.0709
Validation loss improved from -0.1042 to -0.1056 in epoch 87. Saving model...
Validation loss improved from -0.1056 to -0.1114 in epoch 88. Saving model...
Validation loss improved from -0.1114 to -0.1169 in epoch 89. Saving model...
Validation loss improved from -0.1169 to -0.1227 in epoch 90. Saving model...
Validation loss improved from -0.1227 to -0.1279 in epoch 91. Saving model...
Epoch 91/5000 - Train Loss: 0.0325, Val Loss: -0.1279
Validation loss improved from -0.1279 to -0.1332 in epoch 92. Saving model...
Validation loss improved from -0.1332 to -0.1384 in epoch 93. Saving model...
Validation loss improved from -0.1384 to -0.1432 in epoch 94. Saving model...
Validation loss improved from -0.1432 to -0.1470 in epoch 95. Saving model...
Validation loss improved from -0.1470 to -0.1495 in epoch 96. Saving model...
Validation loss improved from -0.1495 to -0.1501 in epoch 97. Saving model...
Epoch 101/5000 - Train Loss: -0.0327, Val Loss: 0.0323
Epoch 111/5000 - Train Loss: -0.0683, Val Loss: 24.3990
Epoch 121/5000 - Train Loss: -0.0922, Val Loss: 25.2097
Epoch 131/5000 - Train Loss: -0.1096, Val Loss: 30.9105
Epoch 141/5000 - Train Loss: -0.1230, Val Loss: 34.1688
Epoch 151/5000 - Train Loss: -0.1327, Val Loss: 29.2911
Epoch 161/5000 - Train Loss: -0.1436, Val Loss: 30.4421
Epoch 171/5000 - Train Loss: -0.1519, Val Loss: 35.3345
Epoch 181/5000 - Train Loss: -0.1599, Val Loss: 34.9123
Epoch 191/5000 - Train Loss: -0.1678, Val Loss: 42.0832
Epoch 201/5000 - Train Loss: -0.1749, Val Loss: 44.7697
Epoch 211/5000 - Train Loss: -0.1828, Val Loss: 44.4999
Epoch 221/5000 - Train Loss: -0.1896, Val Loss: 50.2949
Epoch 231/5000 - Train Loss: -0.1913, Val Loss: 15.5053
Epoch 241/5000 - Train Loss: -0.2022, Val Loss: 39.4024
Epoch 251/5000 - Train Loss: -0.2109, Val Loss: 43.1608
Epoch 261/5000 - Train Loss: -0.2184, Val Loss: 39.5413
Epoch 271/5000 - Train Loss: -0.2254, Val Loss: 16.1320
Epoch 281/5000 - Train Loss: -0.2355, Val Loss: 15.8435
Validation loss improved from -0.1501 to -0.2235 in epoch 284. Saving model...
Epoch 291/5000 - Train Loss: -0.1173, Val Loss: -0.1742
Epoch 301/5000 - Train Loss: -0.1626, Val Loss: -0.2115
Validation loss improved from -0.2235 to -0.2237 in epoch 305. Saving model...
Validation loss improved from -0.2237 to -0.2266 in epoch 306. Saving model...
Validation loss improved from -0.2266 to -0.2295 in epoch 307. Saving model...
Validation loss improved from -0.2295 to -0.2323 in epoch 308. Saving model...
Validation loss improved from -0.2323 to -0.2349 in epoch 309. Saving model...
Validation loss improved from -0.2349 to -0.2375 in epoch 310. Saving model...
Validation loss improved from -0.2375 to -0.2399 in epoch 311. Saving model...
Epoch 311/5000 - Train Loss: -0.1979, Val Loss: -0.2399
Validation loss improved from -0.2399 to -0.2424 in epoch 312. Saving model...
Validation loss improved from -0.2424 to -0.2445 in epoch 313. Saving model...
Validation loss improved from -0.2445 to -0.2467 in epoch 314. Saving model...
Validation loss improved from -0.2467 to -0.2489 in epoch 315. Saving model...
Validation loss improved from -0.2489 to -0.2512 in epoch 316. Saving model...
Validation loss improved from -0.2512 to -0.2535 in epoch 317. Saving model...
Validation loss improved from -0.2535 to -0.2558 in epoch 318. Saving model...
Validation loss improved from -0.2558 to -0.2581 in epoch 319. Saving model...
Validation loss improved from -0.2581 to -0.2604 in epoch 320. Saving model...
Validation loss improved from -0.2604 to -0.2626 in epoch 321. Saving model...
Epoch 321/5000 - Train Loss: -0.2248, Val Loss: -0.2626
Validation loss improved from -0.2626 to -0.2648 in epoch 322. Saving model...
Validation loss improved from -0.2648 to -0.2667 in epoch 323. Saving model...
Validation loss improved from -0.2667 to -0.2686 in epoch 324. Saving model...
Validation loss improved from -0.2686 to -0.2704 in epoch 325. Saving model...
Validation loss improved from -0.2704 to -0.2721 in epoch 326. Saving model...
Validation loss improved from -0.2721 to -0.2738 in epoch 327. Saving model...
Validation loss improved from -0.2738 to -0.2755 in epoch 328. Saving model...
Validation loss improved from -0.2755 to -0.2770 in epoch 329. Saving model...
Validation loss improved from -0.2770 to -0.2787 in epoch 330. Saving model...
Validation loss improved from -0.2787 to -0.2803 in epoch 331. Saving model...
Epoch 331/5000 - Train Loss: -0.2466, Val Loss: -0.2803
Validation loss improved from -0.2803 to -0.2818 in epoch 332. Saving model...
Validation loss improved from -0.2818 to -0.2833 in epoch 333. Saving model...
Validation loss improved from -0.2833 to -0.2847 in epoch 334. Saving model...
Validation loss improved from -0.2847 to -0.2862 in epoch 335. Saving model...
Validation loss improved from -0.2862 to -0.2875 in epoch 336. Saving model...
Validation loss improved from -0.2875 to -0.2887 in epoch 337. Saving model...
Validation loss improved from -0.2887 to -0.2902 in epoch 338. Saving model...
Validation loss improved from -0.2902 to -0.2916 in epoch 339. Saving model...
Validation loss improved from -0.2916 to -0.2928 in epoch 340. Saving model...
Validation loss improved from -0.2928 to -0.2941 in epoch 341. Saving model...
Epoch 341/5000 - Train Loss: -0.2643, Val Loss: -0.2941
Validation loss improved from -0.2941 to -0.2954 in epoch 342. Saving model...
Validation loss improved from -0.2954 to -0.2966 in epoch 343. Saving model...
Validation loss improved from -0.2966 to -0.2977 in epoch 344. Saving model...
Validation loss improved from -0.2977 to -0.2988 in epoch 345. Saving model...
Validation loss improved from -0.2988 to -0.2999 in epoch 346. Saving model...
Validation loss improved from -0.2999 to -0.3011 in epoch 347. Saving model...
Validation loss improved from -0.3011 to -0.3023 in epoch 348. Saving model...
Validation loss improved from -0.3023 to -0.3035 in epoch 349. Saving model...
Validation loss improved from -0.3035 to -0.3050 in epoch 350. Saving model...
Validation loss improved from -0.3050 to -0.3062 in epoch 351. Saving model...
Epoch 351/5000 - Train Loss: -0.2813, Val Loss: -0.3062
Validation loss improved from -0.3062 to -0.3075 in epoch 352. Saving model...
Validation loss improved from -0.3075 to -0.3085 in epoch 353. Saving model...
Validation loss improved from -0.3085 to -0.3096 in epoch 354. Saving model...
Validation loss improved from -0.3096 to -0.3107 in epoch 355. Saving model...
Validation loss improved from -0.3107 to -0.3118 in epoch 356. Saving model...
Validation loss improved from -0.3118 to -0.3131 in epoch 357. Saving model...
Validation loss improved from -0.3131 to -0.3142 in epoch 358. Saving model...
Validation loss improved from -0.3142 to -0.3154 in epoch 359. Saving model...
Validation loss improved from -0.3154 to -0.3166 in epoch 360. Saving model...
Validation loss improved from -0.3166 to -0.3176 in epoch 361. Saving model...
Epoch 361/5000 - Train Loss: -0.2958, Val Loss: -0.3176
Validation loss improved from -0.3176 to -0.3187 in epoch 362. Saving model...
Validation loss improved from -0.3187 to -0.3199 in epoch 363. Saving model...
Validation loss improved from -0.3199 to -0.3210 in epoch 364. Saving model...
Validation loss improved from -0.3210 to -0.3220 in epoch 365. Saving model...
Validation loss improved from -0.3220 to -0.3231 in epoch 366. Saving model...
Validation loss improved from -0.3231 to -0.3239 in epoch 367. Saving model...
Validation loss improved from -0.3239 to -0.3248 in epoch 368. Saving model...
Validation loss improved from -0.3248 to -0.3257 in epoch 369. Saving model...
Validation loss improved from -0.3257 to -0.3268 in epoch 370. Saving model...
Validation loss improved from -0.3268 to -0.3276 in epoch 371. Saving model...
Epoch 371/5000 - Train Loss: -0.3078, Val Loss: -0.3276
Validation loss improved from -0.3276 to -0.3286 in epoch 372. Saving model...
Validation loss improved from -0.3286 to -0.3297 in epoch 373. Saving model...
Validation loss improved from -0.3297 to -0.3305 in epoch 374. Saving model...
Validation loss improved from -0.3305 to -0.3314 in epoch 375. Saving model...
Validation loss improved from -0.3314 to -0.3319 in epoch 376. Saving model...
Validation loss improved from -0.3319 to -0.3327 in epoch 377. Saving model...
Validation loss improved from -0.3327 to -0.3338 in epoch 378. Saving model...
Validation loss improved from -0.3338 to -0.3350 in epoch 379. Saving model...
Validation loss improved from -0.3350 to -0.3363 in epoch 380. Saving model...
Validation loss improved from -0.3363 to -0.3374 in epoch 381. Saving model...
Epoch 381/5000 - Train Loss: -0.3181, Val Loss: -0.3374
Validation loss improved from -0.3374 to -0.3382 in epoch 382. Saving model...
Validation loss improved from -0.3382 to -0.3390 in epoch 383. Saving model...
Validation loss improved from -0.3390 to -0.3403 in epoch 384. Saving model...
Validation loss improved from -0.3403 to -0.3412 in epoch 385. Saving model...
Validation loss improved from -0.3412 to -0.3422 in epoch 386. Saving model...
Validation loss improved from -0.3422 to -0.3433 in epoch 387. Saving model...
Validation loss improved from -0.3433 to -0.3438 in epoch 388. Saving model...
Validation loss improved from -0.3438 to -0.3449 in epoch 389. Saving model...
Validation loss improved from -0.3449 to -0.3460 in epoch 390. Saving model...
Validation loss improved from -0.3460 to -0.3467 in epoch 391. Saving model...
Epoch 391/5000 - Train Loss: -0.3279, Val Loss: -0.3467
Validation loss improved from -0.3467 to -0.3476 in epoch 392. Saving model...
Validation loss improved from -0.3476 to -0.3486 in epoch 393. Saving model...
Validation loss improved from -0.3486 to -0.3496 in epoch 394. Saving model...
Validation loss improved from -0.3496 to -0.3507 in epoch 395. Saving model...
Validation loss improved from -0.3507 to -0.3508 in epoch 397. Saving model...
Validation loss improved from -0.3508 to -0.3522 in epoch 398. Saving model...
Validation loss improved from -0.3522 to -0.3535 in epoch 399. Saving model...
Validation loss improved from -0.3535 to -0.3544 in epoch 400. Saving model...
Validation loss improved from -0.3544 to -0.3551 in epoch 401. Saving model...
Epoch 401/5000 - Train Loss: -0.3366, Val Loss: -0.3551
Validation loss improved from -0.3551 to -0.3560 in epoch 402. Saving model...
Validation loss improved from -0.3560 to -0.3569 in epoch 403. Saving model...
Validation loss improved from -0.3569 to -0.3576 in epoch 404. Saving model...
Validation loss improved from -0.3576 to -0.3581 in epoch 405. Saving model...
Validation loss improved from -0.3581 to -0.3593 in epoch 406. Saving model...
Validation loss improved from -0.3593 to -0.3601 in epoch 407. Saving model...
Validation loss improved from -0.3601 to -0.3606 in epoch 408. Saving model...
Validation loss improved from -0.3606 to -0.3612 in epoch 409. Saving model...
Validation loss improved from -0.3612 to -0.3623 in epoch 410. Saving model...
Validation loss improved from -0.3623 to -0.3630 in epoch 411. Saving model...
Epoch 411/5000 - Train Loss: -0.3447, Val Loss: -0.3630
Validation loss improved from -0.3630 to -0.3638 in epoch 412. Saving model...
Validation loss improved from -0.3638 to -0.3645 in epoch 413. Saving model...
Validation loss improved from -0.3645 to -0.3653 in epoch 414. Saving model...
Validation loss improved from -0.3653 to -0.3656 in epoch 415. Saving model...
Validation loss improved from -0.3656 to -0.3664 in epoch 416. Saving model...
Validation loss improved from -0.3664 to -0.3671 in epoch 417. Saving model...
Validation loss improved from -0.3671 to -0.3676 in epoch 418. Saving model...
Validation loss improved from -0.3676 to -0.3680 in epoch 419. Saving model...
Validation loss improved from -0.3680 to -0.3689 in epoch 420. Saving model...
Validation loss improved from -0.3689 to -0.3699 in epoch 421. Saving model...
Epoch 421/5000 - Train Loss: -0.3517, Val Loss: -0.3699
Validation loss improved from -0.3699 to -0.3705 in epoch 423. Saving model...
Validation loss improved from -0.3705 to -0.3710 in epoch 424. Saving model...
Validation loss improved from -0.3710 to -0.3717 in epoch 425. Saving model...
Validation loss improved from -0.3717 to -0.3727 in epoch 426. Saving model...
Validation loss improved from -0.3727 to -0.3729 in epoch 427. Saving model...
Validation loss improved from -0.3729 to -0.3739 in epoch 428. Saving model...
Validation loss improved from -0.3739 to -0.3746 in epoch 429. Saving model...
Validation loss improved from -0.3746 to -0.3753 in epoch 430. Saving model...
Validation loss improved from -0.3753 to -0.3759 in epoch 431. Saving model...
Epoch 431/5000 - Train Loss: -0.3590, Val Loss: -0.3759
Validation loss improved from -0.3759 to -0.3765 in epoch 432. Saving model...
Validation loss improved from -0.3765 to -0.3774 in epoch 433. Saving model...
Validation loss improved from -0.3774 to -0.3776 in epoch 434. Saving model...
Validation loss improved from -0.3776 to -0.3783 in epoch 435. Saving model...
Validation loss improved from -0.3783 to -0.3794 in epoch 436. Saving model...
Validation loss improved from -0.3794 to -0.3798 in epoch 437. Saving model...
Validation loss improved from -0.3798 to -0.3799 in epoch 438. Saving model...
Validation loss improved from -0.3799 to -0.3802 in epoch 439. Saving model...
Validation loss improved from -0.3802 to -0.3810 in epoch 440. Saving model...
Validation loss improved from -0.3810 to -0.3816 in epoch 441. Saving model...
Epoch 441/5000 - Train Loss: -0.3657, Val Loss: -0.3816
Validation loss improved from -0.3816 to -0.3824 in epoch 442. Saving model...
Validation loss improved from -0.3824 to -0.3830 in epoch 443. Saving model...
Validation loss improved from -0.3830 to -0.3840 in epoch 447. Saving model...
Validation loss improved from -0.3840 to -0.3856 in epoch 448. Saving model...
Validation loss improved from -0.3856 to -0.3859 in epoch 449. Saving model...
Validation loss improved from -0.3859 to -0.3865 in epoch 450. Saving model...
Validation loss improved from -0.3865 to -0.3870 in epoch 451. Saving model...

In [28]:
trainer.model

distModel(
  (input_layer): Linear(in_features=3, out_features=50, bias=True)
  (hidden_layers): ModuleList()
  (output_mean_layer): Linear(in_features=50, out_features=1, bias=True)
  (output_sd_layer): Linear(in_features=50, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.05, inplace=False)
)

In [29]:
#trainer.predict(X=trainer.X_test)

In [30]:
trainer.evaluate_gaussian_nll()
trainer.evaluate_standardized_residuals()

Baseline Gaussian NLL Loss: 0.4348
Model Gaussian NLL Loss: -0.9925
KS test against N(0,1): statistic = 0.0896, p-value = 0.0758
✅ The standardized residuals do not significantly differ from a standard normal distribution — model variance estimates appear well-calibrated.
Saved: residual_diagnostics\z_histogram.png
Saved: residual_diagnostics\z_qqplot.png

(np.float64(0.08959054354084939), np.float64(0.07581196982910754))

In [31]:
'''# Inputs
x = np.array([[-1.266313, -0.405118, 0.612491]])

# Extract weights from model
state_dict = trainer.model.state_dict()
w0 = state_dict['input_layer.weight'].cpu().numpy()
b0 = state_dict['input_layer.bias'].cpu().numpy()

w1 = state_dict['hidden_layers.0.weight'].cpu().numpy()
b1 = state_dict['hidden_layers.0.bias'].cpu().numpy()

w_mean = state_dict['output_mean_layer.weight'].cpu().numpy()
b_mean = state_dict['output_mean_layer.bias'].cpu().numpy()

w_sd = state_dict['output_sd_layer.weight'].cpu().numpy()
b_sd = state_dict['output_sd_layer.bias'].cpu().numpy()

# Manual forward pass
def relu(x): return np.maximum(0, x)

h0 = relu(x.dot(w0.T) + b0)
h1 = relu(h0.dot(w1.T) + b1)
mean = h1.dot(w_mean.T) + b_mean
sd = relu(h1.dot(w_sd.T) + b_sd)

print("Manual mean:", mean)
print("Manual std:", sd)'''

'# Inputs\nx = np.array([[-1.266313, -0.405118, 0.612491]])\n\n# Extract weights from model\nstate_dict = trainer.model.state_dict()\nw0 = state_dict[\'input_layer.weight\'].cpu().numpy()\nb0 = state_dict[\'input_layer.bias\'].cpu().numpy()\n\nw1 = state_dict[\'hidden_layers.0.weight\'].cpu().numpy()\nb1 = state_dict[\'hidden_layers.0.bias\'].cpu().numpy()\n\nw_mean = state_dict[\'output_mean_layer.weight\'].cpu().numpy()\nb_mean = state_dict[\'output_mean_layer.bias\'].cpu().numpy()\n\nw_sd = state_dict[\'output_sd_layer.weight\'].cpu().numpy()\nb_sd = state_dict[\'output_sd_layer.bias\'].cpu().numpy()\n\n# Manual forward pass\ndef relu(x): return np.maximum(0, x)\n\nh0 = relu(x.dot(w0.T) + b0)\nh1 = relu(h0.dot(w1.T) + b1)\nmean = h1.dot(w_mean.T) + b_mean\nsd = relu(h1.dot(w_sd.T) + b_sd)\n\nprint("Manual mean:", mean)\nprint("Manual std:", sd)'

In [32]:
cons = trainer.constraint_build()
cons.to_csv('constraints.csv')

In [33]:
cons = pd.read_csv('constraints.csv', index_col=0)
pd.set_option('display.precision', 10)
cons

,intercept,layer,node,node_0,node_1,node_2,node_3,node_4,node_5,node_6,...,node_40,node_41,node_42,node_43,node_44,node_45,node_46,node_47,node_48,node_49
0,0.6779146000,0,0,-0.188254100,-0.638588600,-0.172332930,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.2116805300,0,1,0.386523070,-0.110227740,-0.287262950,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.4024943400,0,2,0.058709030,0.038973458,-0.097894270,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.4906951800,0,3,0.147300470,-0.266274630,-0.254659400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.2432052800,0,4,-0.166126530,0.225335700,-0.039615393,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.2330293400,0,5,-0.530603230,-0.115756400,0.009267576,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.3960148000,0,6,-0.317019370,-0.130347010,0.129868790,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.5506942000,0,7,0.435406660,0.332051600,-0.261411250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.3613306000,0,8,-0.422160450,0.253077660,0.064485540,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.3473700300,0,9,-0.286944750,0.267391400,-0.500320200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.5031466500,0,10,0.264627900,0.157630340,0.491575000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.1588855500,0,11,-0.154738780,-0.382230580,0.587745130,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,-0.4671758700,0,12,-0.112458950,-0.560298440,-0.220239710,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.4028715500,0,13,0.472895500,-0.374444600,0.112308030,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0.5030685700,0,14,-0.577758000,-0.180992130,-0.217675220,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.5726486400,0,15,-0.185376840,-0.304351800,-0.407905580,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-0.4231214800,0,16,0.171264570,0.485692650,0.154053580,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0.1858620300,0,17,0.169223650,-0.358322350,0.227230150,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0.4803976000,0,18,0.143525480,0.438947560,0.309158920,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,-0.1442130000,0,19,0.595597600,0.226622370,-0.282417420,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0.2532997400,0,20,0.337803160,-0.087679260,0.044503372,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.0692343340,0,21,-0.650639500,0.222534790,0.208441150,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.5482769000,0,22,0.152590020,0.216392600,0.234440620,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,-0.5683028700,0,23,-0.239062800,-0.426520940,-0.471242280,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.0243325460,0,24,-0.467103100,-0.166893840,-0.283600540,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,-0.5969848600,0,25,0.502074700,-0.269588620,-0.227137770,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0.2362179800,0,26,-0.379917680,-0.330523430,0.338462800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0.2645849300,0,27,0.847569200,0.290154700,-0.102551760,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.0854567900,0,28,-0.207018450,-0.506353400,0.314390100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.3681433500,0,29,0.504355400,-0.474071260,0.410396300,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,-0.1956723600,0,30,-0.296201170,-0.570346830,0.185402210,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.3902036800,0,31,-0.514525200,-0.300868120,0.550772800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,0.3202478600,0,32,-0.484468100,-0.362235550,-0.169693700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,-0.2616923500,0,33,0.448188100,0.389234960,0.421817750,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,-0.1455376100,0,34,-0.307157500,-0.296509000,0.347551760,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0.4395837800,0,35,0.515654560,0.415240140,0.228798480,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,-0.5199517000,0,36,-0.147730540,0.167115480,-0.436357500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0.1799985800,0,37,-0.089597470,0.571117800,0.040968490,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,-0.4369003500,0,38,0.429488240,0.360042000,0.598737800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,0.0207971650,0,39,0.302440050,-0.547140840,-0.237386090,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.4701013000,0,40,0.011645005,0.521631960,0.060855190,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-0.0049348124,0,41,0.032243673,0.247972830,-0.360040600,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,-0.3499139800,0,42,-0.570944130,0.078780310,-0.179185120,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,-0.4416936000,0,43,0.232718150,0.339997380,-0.488338740,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,-0.0602611300,0,44,0.179439110,0.248813300,0.256883170,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,0.0095922420,0,45,0.313624800,-0.343475600,-0.242798250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,0.1212959300,0,46,-0.321471360,0.535315000,0.259233100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0.0675924100,0,47,0.037422374,0.209395450,-0.501659800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,0.5733384000,0,48,0.501361370,-0.455820920,-0.104085244,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,0.0300184710,0,49,-0.383781820,-0.047328413,-0.359941800,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,-0.1231536640,1,0,-0.508333800,0.227440640,-0.035241675,0.060940510,0.27535906,-0.047195440,-0.0697821100,...,-0.058422740,-0.257326200,0.10053643,-0.179645480,0.04647625,-0.07034372,-0.022298522,0.047142647,-0.075901695,0.027645648
0,0.0478547800,2,0,0.074814620,-0.175501640,-0.119878836,-0.050251435,0.11893894,-0.086901166,-0.0007140661,...,-0.010156792,-0.110943235,-0.10254426,0.048941027,0.14051480,0.07614187,-0.120035400,-0.041748505,0.132338030,0.106237390

In [34]:

'''#contextual_var = trainer.X_test
contextual_var = trainer.X_test.iloc[[0]]
contextual_var.reset_index(drop=True, inplace=True)
contextual_var'''

'#contextual_var = trainer.X_test\ncontextual_var = trainer.X_test.iloc[[0]]\ncontextual_var.reset_index(drop=True, inplace=True)\ncontextual_var'

In [35]:
'''row = pd.DataFrame([{
    'x1': -1.266313,
    'x2': -0.405118,
    'price': 30.0
}])

def preict_one_row(row):
    # Predict
    mean_pred, sd_pred = trainer.predict(row, unscale=True)
    print("Mean prediction:", mean_pred)
    print("Standard deviation prediction:", sd_pred)

preict_one_row(row)'''

'row = pd.DataFrame([{\n    \'x1\': -1.266313,\n    \'x2\': -0.405118,\n    \'price\': 30.0\n}])\n\ndef preict_one_row(row):\n    # Predict\n    mean_pred, sd_pred = trainer.predict(row, unscale=True)\n    print("Mean prediction:", mean_pred)\n    print("Standard deviation prediction:", sd_pred)\n\npreict_one_row(row)'

In [36]:
def model_definition(contextual_var, n_sc, n_preds):
    model = pyo.ConcreteModel()
    
    model.N = pyo.RangeSet(0,n_preds-1)
    model.W = pyo.RangeSet(1,n_sc) # scenarios

    pi = [1/n_sc for i in range(n_sc)]

    model.var_ind = pyo.Set(initialize=contextual_var.columns.sort_values())

    model.x = pyo.Var(model.var_ind, model.N) # price

    model.y = pyo.Var(pyo.Any, dense=False, domain=pyo.Reals)

    model.rent = pyo.Var(model.W, within=pyo.Reals) # rentabilidad per scenario

    #definition of the objective function
    def obj_expression(model):
        return sum(pi[w-1] * model.rent[w] for w in model.W)
    model.OBJ = pyo.Objective(rule=obj_expression, sense=pyo.maximize)

    #definition of the constraints
    def rent_expression(model, w):
        return model.rent[w] == sum(model.y['demand', n, w]*model.x['price',n] for n in model.N)
    model.rent_expression = pyo.Constraint(model.W, rule=rent_expression)

    #constraint for fixing contextual information
    def const9_rule(model,x_ind,n):
        if x_ind=='price':
            return pyo.Constraint.Skip
        else:
            return model.x[x_ind,n] == contextual_var.loc[n,x_ind]
    model.const9 = pyo.Constraint(model.var_ind, model.N, rule=const9_rule)

    P_max = 30
    # max price constraint for each price
    def max_price_expression(model, n):
        return model.x['price', n] <= P_max

    model.max_price_expression = pyo.Constraint(model.N, rule=max_price_expression)

    def min_price_expression(model, n):
        return model.x['price', n] >= 0
    model.min_price_expression = pyo.Constraint(model.N, rule=min_price_expression)

    return model

In [37]:
n_preds = 2
n_sc =  30

contextual_var = trainer.X[trainer.X.index.isin(trainer.test_indices)]
contextual_var = contextual_var.iloc[:n_preds]
contextual_var.reset_index(drop=True, inplace=True)
contextual_var

           price            x1            x2
0  15.2341136747  0.3745401188  0.1851329288
1  28.1250916104  0.7319939418  0.8729458359

In [38]:
'''n_preds = 3
n_sc =  30

contextual_var = trainer.X_test.iloc[:n_preds]
contextual_var.reset_index(drop=True, inplace=True)
contextual_var'''

'n_preds = 3\nn_sc =  30\n\ncontextual_var = trainer.X_test.iloc[:n_preds]\ncontextual_var.reset_index(drop=True, inplace=True)\ncontextual_var'

In [39]:
model = model_definition(contextual_var, n_sc, n_preds)
const_embed(model=trainer, opt_model=model, constaints=cons, outcome='demand', n_scenarios=n_sc, n_preds=n_preds)

In [40]:
opt = pyo.SolverFactory('gurobi_direct')
opt.options['threads'] = 0
opt.options['NonConvex'] = 2
results = opt.solve(model, tee=True)

Set parameter OutputFlag to value 1
Set parameter Threads to value 0
Set parameter NonConvex to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i5-13500, instruction set [SSE2|AVX|AVX2]
Thread count: 14 physical cores, 20 logical processors, using up to 20 threads

Non-default parameters:
NonConvex  2

Optimize a model with 372 rows, 300 columns and 1492 nonzeros
Model fingerprint: 0x1a3f5298
Model has 30 quadratic constraints
Variable types: 200 continuous, 100 integer (100 binary)
Coefficient statistics:
  Matrix range     [7e-04, 1e+03]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [3e-02, 3e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e-02, 1e+03]
Presolve removed 95 rows and 92 columns
Presolve time: 0.12s
Presolved: 398 rows, 270 columns, 1188 nonzeros
Presolved model has 60 bilinear constraint(s)

Solving non-convex MIQCP

Variable types: 199 continuous, 71 integer (71 binary)
Found heuristic solution: objective 144.6484830

Root relaxation: objective 6.814967e+02, 270 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  681.49672    0   99  144.64848  681.49672   371%     -    0s
     0     0  346.96727    0  123  144.64848  346.96727   140%     -    0s
     0     0  346.96727    0  124  144.64848  346.96727   140%     -    0s
H    0     0                     177.9159239  346.96727  95.0%     -    0s
     0     0  301.63015    0  121  177.91592  301.63015  69.5%     -    0s
     0     0  209.99779    0  121  177.91592  209.99779  18.0%     -    0s
     0     0  205.15974    0  124  177.91592  205.15974  15.3%     -    0s
H    0     0                     177.9734659  205.15974  15.3%     -    0s
H    0     0                     183.4761441  205.15974  11.8%     -    0s
H    0     0                     184.0007608  205.15974  11.5%     -    0s
H    0     0                     184.2786050  205.15974  11.3%     -    0s
H    0     0                     184.2816238  205.15974  11.3%     -    0s
H    0     0                     185.3207838  186.22749  0.49%     -    0s
     0     0  186.13217    0  124  185.32078  186.13217  0.44%     -    0s
H    0     0                     185.3460187  186.13217  0.42%     -    0s
     0     0  185.58439    0  125  185.34602  185.58439  0.13%     -    0s
H    0     0                     185.4429088  185.58439  0.08%     -    0s
H    0     0                     185.4641992  185.58439  0.06%     -    0s

Cutting planes:
  Gomory: 7
  Cover: 41
  Implied bound: 11
  Clique: 33
  MIR: 27
  Flow cover: 21
  RLT: 294
  Relax-and-lift: 100
  BQP: 23

Explored 1 nodes (1021 simplex iterations) in 0.52 seconds (0.60 work units)
Thread count was 20 (of 20 available processors)

Solution count 10: 185.464 185.443 185.346 ... 177.916

Optimal solution found (tolerance 1.00e-04)
Best objective 1.854641992053e+02, best bound 1.854661311753e+02, gap 0.0010%

In [41]:
print(value(model.x['price', 0]))
print((value(model.x['price', 0]) * trainer.X_std[0]) + trainer.X_mean[0])
print((value(model.x['price', 0] - trainer.X_mean[0])) / trainer.X_std[0])

10.283496730540044
79.51160113794145
-1.7020796172793466

In [42]:
for c in model.component_objects(Constraint, active=True):
    print(f"Constraint component: {c.name}")
    for index in c:
        print(f"  {index}: {c[index].expr}")

Constraint component: rent_expression
  1: rent[1]  ==  y[demand,0,1]*x[price,0] + y[demand,1,1]*x[price,1]
  2: rent[2]  ==  y[demand,0,2]*x[price,0] + y[demand,1,2]*x[price,1]
  3: rent[3]  ==  y[demand,0,3]*x[price,0] + y[demand,1,3]*x[price,1]
  4: rent[4]  ==  y[demand,0,4]*x[price,0] + y[demand,1,4]*x[price,1]
  5: rent[5]  ==  y[demand,0,5]*x[price,0] + y[demand,1,5]*x[price,1]
  6: rent[6]  ==  y[demand,0,6]*x[price,0] + y[demand,1,6]*x[price,1]
  7: rent[7]  ==  y[demand,0,7]*x[price,0] + y[demand,1,7]*x[price,1]
  8: rent[8]  ==  y[demand,0,8]*x[price,0] + y[demand,1,8]*x[price,1]
  9: rent[9]  ==  y[demand,0,9]*x[price,0] + y[demand,1,9]*x[price,1]
  10: rent[10]  ==  y[demand,0,10]*x[price,0] + y[demand,1,10]*x[price,1]
  11: rent[11]  ==  y[demand,0,11]*x[price,0] + y[demand,1,11]*x[price,1]
  12: rent[12]  ==  y[demand,0,12]*x[price,0] + y[demand,1,12]*x[price,1]
  13: rent[13]  ==  y[demand,0,13]*x[price,0] + y[demand,1,13]*x[price,1]
  14: rent[14]  ==  y[demand,0,14]*x[price,0] + y[demand,1,14]*x[price,1]
  15: rent[15]  ==  y[demand,0,15]*x[price,0] + y[demand,1,15]*x[price,1]
  16: rent[16]  ==  y[demand,0,16]*x[price,0] + y[demand,1,16]*x[price,1]
  17: rent[17]  ==  y[demand,0,17]*x[price,0] + y[demand,1,17]*x[price,1]
  18: rent[18]  ==  y[demand,0,18]*x[price,0] + y[demand,1,18]*x[price,1]
  19: rent[19]  ==  y[demand,0,19]*x[price,0] + y[demand,1,19]*x[price,1]
  20: rent[20]  ==  y[demand,0,20]*x[price,0] + y[demand,1,20]*x[price,1]
  21: rent[21]  ==  y[demand,0,21]*x[price,0] + y[demand,1,21]*x[price,1]
  22: rent[22]  ==  y[demand,0,22]*x[price,0] + y[demand,1,22]*x[price,1]
  23: rent[23]  ==  y[demand,0,23]*x[price,0] + y[demand,1,23]*x[price,1]
  24: rent[24]  ==  y[demand,0,24]*x[price,0] + y[demand,1,24]*x[price,1]
  25: rent[25]  ==  y[demand,0,25]*x[price,0] + y[demand,1,25]*x[price,1]
  26: rent[26]  ==  y[demand,0,26]*x[price,0] + y[demand,1,26]*x[price,1]
  27: rent[27]  ==  y[demand,0,27]*x[price,0] + y[demand,1,27]*x[price,1]
  28: rent[28]  ==  y[demand,0,28]*x[price,0] + y[demand,1,28]*x[price,1]
  29: rent[29]  ==  y[demand,0,29]*x[price,0] + y[demand,1,29]*x[price,1]
  30: rent[30]  ==  y[demand,0,30]*x[price,0] + y[demand,1,30]*x[price,1]
Constraint component: const9
  ('x1', 0): x[x1,0]  ==  0.3745401188473625
  ('x1', 1): x[x1,1]  ==  0.7319939418114051
  ('x2', 0): x[x2,0]  ==  0.18513292883861965
  ('x2', 1): x[x2,1]  ==  0.8729458358764083
Constraint component: max_price_expression
  0: x[price,0]  <=  30
  1: x[price,1]  <=  30
Constraint component: min_price_expression
  0: 0  <=  x[price,0]
  1: 0  <=  x[price,1]
Constraint component: constraint_1_layer0_node0_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.1882541 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.6385886 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.17233293 + 0.6779146  <=  v[demand,0,0,0]
Constraint component: constraint_2_layer0_node0_pred0demand
  None: v[demand,0,0,0]  <=  1000.0*v_ind[demand,0,0,0]
Constraint component: constraint_3_layer0_node0_pred0demand
  None: v[demand,0,0,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.1882541 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.6385886 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.17233293 + 0.6779146 + 1000.0*(1 - v_ind[demand,0,0,0])
Constraint component: constraint_1_layer0_node1_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.38652307 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.11022774 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.28726295 + 0.21168053  <=  v[demand,0,1,0]
Constraint component: constraint_2_layer0_node1_pred0demand
  None: v[demand,0,1,0]  <=  1000.0*v_ind[demand,0,1,0]
Constraint component: constraint_3_layer0_node1_pred0demand
  None: v[demand,0,1,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.38652307 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.11022774 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.28726295 + 0.21168053 + 1000.0*(1 - v_ind[demand,0,1,0])
Constraint component: constraint_1_layer0_node2_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.05870903 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.038973458 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.09789427 + 0.40249434  <=  v[demand,0,2,0]
Constraint component: constraint_2_layer0_node2_pred0demand
  None: v[demand,0,2,0]  <=  1000.0*v_ind[demand,0,2,0]
Constraint component: constraint_3_layer0_node2_pred0demand
  None: v[demand,0,2,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.05870903 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.038973458 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.09789427 + 0.40249434 + 1000.0*(1 - v_ind[demand,0,2,0])
Constraint component: constraint_1_layer0_node3_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.14730047 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.26627463 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.2546594 + 0.49069518  <=  v[demand,0,3,0]
Constraint component: constraint_2_layer0_node3_pred0demand
  None: v[demand,0,3,0]  <=  1000.0*v_ind[demand,0,3,0]
Constraint component: constraint_3_layer0_node3_pred0demand
  None: v[demand,0,3,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.14730047 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.26627463 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.2546594 + 0.49069518 + 1000.0*(1 - v_ind[demand,0,3,0])
Constraint component: constraint_1_layer0_node4_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.16612653 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2253357 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.039615393 - 0.24320528  <=  v[demand,0,4,0]
Constraint component: constraint_2_layer0_node4_pred0demand
  None: v[demand,0,4,0]  <=  1000.0*v_ind[demand,0,4,0]
Constraint component: constraint_3_layer0_node4_pred0demand
  None: v[demand,0,4,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.16612653 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2253357 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.039615393 - 0.24320528 + 1000.0*(1 - v_ind[demand,0,4,0])
Constraint component: constraint_1_layer0_node5_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.53060323 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.1157564 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.009267576 + 0.23302934  <=  v[demand,0,5,0]
Constraint component: constraint_2_layer0_node5_pred0demand
  None: v[demand,0,5,0]  <=  1000.0*v_ind[demand,0,5,0]
Constraint component: constraint_3_layer0_node5_pred0demand
  None: v[demand,0,5,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.53060323 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.1157564 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.009267576 + 0.23302934 + 1000.0*(1 - v_ind[demand,0,5,0])
Constraint component: constraint_1_layer0_node6_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.31701937 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.13034701 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.12986879 + 0.3960148  <=  v[demand,0,6,0]
Constraint component: constraint_2_layer0_node6_pred0demand
  None: v[demand,0,6,0]  <=  1000.0*v_ind[demand,0,6,0]
Constraint component: constraint_3_layer0_node6_pred0demand
  None: v[demand,0,6,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.31701937 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.13034701 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.12986879 + 0.3960148 + 1000.0*(1 - v_ind[demand,0,6,0])
Constraint component: constraint_1_layer0_node7_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.43540666 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.3320516 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.26141125 + 0.5506942  <=  v[demand,0,7,0]
Constraint component: constraint_2_layer0_node7_pred0demand
  None: v[demand,0,7,0]  <=  1000.0*v_ind[demand,0,7,0]
Constraint component: constraint_3_layer0_node7_pred0demand
  None: v[demand,0,7,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.43540666 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.3320516 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.26141125 + 0.5506942 + 1000.0*(1 - v_ind[demand,0,7,0])
Constraint component: constraint_1_layer0_node8_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.42216045 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.25307766 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.06448554 + 0.3613306  <=  v[demand,0,8,0]
Constraint component: constraint_2_layer0_node8_pred0demand
  None: v[demand,0,8,0]  <=  1000.0*v_ind[demand,0,8,0]
Constraint component: constraint_3_layer0_node8_pred0demand
  None: v[demand,0,8,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.42216045 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.25307766 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.06448554 + 0.3613306 + 1000.0*(1 - v_ind[demand,0,8,0])
Constraint component: constraint_1_layer0_node9_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.28694475 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2673914 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.5003202 + 0.34737003  <=  v[demand,0,9,0]
Constraint component: constraint_2_layer0_node9_pred0demand
  None: v[demand,0,9,0]  <=  1000.0*v_ind[demand,0,9,0]
Constraint component: constraint_3_layer0_node9_pred0demand
  None: v[demand,0,9,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.28694475 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2673914 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.5003202 + 0.34737003 + 1000.0*(1 - v_ind[demand,0,9,0])
Constraint component: constraint_1_layer0_node10_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.2646279 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.15763034 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.491575 + 0.50314665  <=  v[demand,0,10,0]
Constraint component: constraint_2_layer0_node10_pred0demand
  None: v[demand,0,10,0]  <=  1000.0*v_ind[demand,0,10,0]
Constraint component: constraint_3_layer0_node10_pred0demand
  None: v[demand,0,10,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.2646279 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.15763034 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.491575 + 0.50314665 + 1000.0*(1 - v_ind[demand,0,10,0])
Constraint component: constraint_1_layer0_node11_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.15473878 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.38223058 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.58774513 + 0.15888555  <=  v[demand,0,11,0]
Constraint component: constraint_2_layer0_node11_pred0demand
  None: v[demand,0,11,0]  <=  1000.0*v_ind[demand,0,11,0]
Constraint component: constraint_3_layer0_node11_pred0demand
  None: v[demand,0,11,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.15473878 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.38223058 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.58774513 + 0.15888555 + 1000.0*(1 - v_ind[demand,0,11,0])
Constraint component: constraint_1_layer0_node12_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.11245895 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.56029844 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.22023971 - 0.46717587  <=  v[demand,0,12,0]
Constraint component: constraint_2_layer0_node12_pred0demand
  None: v[demand,0,12,0]  <=  1000.0*v_ind[demand,0,12,0]
Constraint component: constraint_3_layer0_node12_pred0demand
  None: v[demand,0,12,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.11245895 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.56029844 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.22023971 - 0.46717587 + 1000.0*(1 - v_ind[demand,0,12,0])
Constraint component: constraint_1_layer0_node13_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.4728955 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.3744446 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.11230803 + 0.40287155  <=  v[demand,0,13,0]
Constraint component: constraint_2_layer0_node13_pred0demand
  None: v[demand,0,13,0]  <=  1000.0*v_ind[demand,0,13,0]
Constraint component: constraint_3_layer0_node13_pred0demand
  None: v[demand,0,13,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.4728955 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.3744446 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.11230803 + 0.40287155 + 1000.0*(1 - v_ind[demand,0,13,0])
Constraint component: constraint_1_layer0_node14_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.577758 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.18099213 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.21767522 + 0.50306857  <=  v[demand,0,14,0]
Constraint component: constraint_2_layer0_node14_pred0demand
  None: v[demand,0,14,0]  <=  1000.0*v_ind[demand,0,14,0]
Constraint component: constraint_3_layer0_node14_pred0demand
  None: v[demand,0,14,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.577758 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.18099213 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.21767522 + 0.50306857 + 1000.0*(1 - v_ind[demand,0,14,0])
Constraint component: constraint_1_layer0_node15_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.18537684 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.3043518 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.40790558 + 0.57264864  <=  v[demand,0,15,0]
Constraint component: constraint_2_layer0_node15_pred0demand
  None: v[demand,0,15,0]  <=  1000.0*v_ind[demand,0,15,0]
Constraint component: constraint_3_layer0_node15_pred0demand
  None: v[demand,0,15,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.18537684 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.3043518 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.40790558 + 0.57264864 + 1000.0*(1 - v_ind[demand,0,15,0])
Constraint component: constraint_1_layer0_node16_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.17126457 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.48569265 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.15405358 - 0.42312148  <=  v[demand,0,16,0]
Constraint component: constraint_2_layer0_node16_pred0demand
  None: v[demand,0,16,0]  <=  1000.0*v_ind[demand,0,16,0]
Constraint component: constraint_3_layer0_node16_pred0demand
  None: v[demand,0,16,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.17126457 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.48569265 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.15405358 - 0.42312148 + 1000.0*(1 - v_ind[demand,0,16,0])
Constraint component: constraint_1_layer0_node17_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.16922365 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.35832235 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.22723015 + 0.18586203  <=  v[demand,0,17,0]
Constraint component: constraint_2_layer0_node17_pred0demand
  None: v[demand,0,17,0]  <=  1000.0*v_ind[demand,0,17,0]
Constraint component: constraint_3_layer0_node17_pred0demand
  None: v[demand,0,17,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.16922365 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.35832235 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.22723015 + 0.18586203 + 1000.0*(1 - v_ind[demand,0,17,0])
Constraint component: constraint_1_layer0_node18_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.14352548 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.43894756 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.30915892 + 0.4803976  <=  v[demand,0,18,0]
Constraint component: constraint_2_layer0_node18_pred0demand
  None: v[demand,0,18,0]  <=  1000.0*v_ind[demand,0,18,0]
Constraint component: constraint_3_layer0_node18_pred0demand
  None: v[demand,0,18,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.14352548 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.43894756 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.30915892 + 0.4803976 + 1000.0*(1 - v_ind[demand,0,18,0])
Constraint component: constraint_1_layer0_node19_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.5955976 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.22662237 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.28241742 - 0.144213  <=  v[demand,0,19,0]
Constraint component: constraint_2_layer0_node19_pred0demand
  None: v[demand,0,19,0]  <=  1000.0*v_ind[demand,0,19,0]
Constraint component: constraint_3_layer0_node19_pred0demand
  None: v[demand,0,19,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.5955976 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.22662237 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.28241742 - 0.144213 + 1000.0*(1 - v_ind[demand,0,19,0])
Constraint component: constraint_1_layer0_node20_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.33780316 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.08767926 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.044503372 + 0.25329974  <=  v[demand,0,20,0]
Constraint component: constraint_2_layer0_node20_pred0demand
  None: v[demand,0,20,0]  <=  1000.0*v_ind[demand,0,20,0]
Constraint component: constraint_3_layer0_node20_pred0demand
  None: v[demand,0,20,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.33780316 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.08767926 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.044503372 + 0.25329974 + 1000.0*(1 - v_ind[demand,0,20,0])
Constraint component: constraint_1_layer0_node21_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.6506395 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.22253479 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.20844115 + 0.069234334  <=  v[demand,0,21,0]
Constraint component: constraint_2_layer0_node21_pred0demand
  None: v[demand,0,21,0]  <=  1000.0*v_ind[demand,0,21,0]
Constraint component: constraint_3_layer0_node21_pred0demand
  None: v[demand,0,21,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*-0.6506395 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.22253479 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.20844115 + 0.069234334 + 1000.0*(1 - v_ind[demand,0,21,0])
Constraint component: constraint_1_layer0_node22_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*0.15259002 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2163926 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.23444062 + 0.5482769  <=  v[demand,0,22,0]
Constraint component: constraint_2_layer0_node22_pred0demand
  None: v[demand,0,22,0]  <=  1000.0*v_ind[demand,0,22,0]
Constraint component: constraint_3_layer0_node22_pred0demand
  None: v[demand,0,22,0]  <=  (x[price,0] - 20.1146255836938)/5.775951226575475*0.15259002 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*0.2163926 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*0.23444062 + 0.5482769 + 1000.0*(1 - v_ind[demand,0,22,0])
Constraint component: constraint_1_layer0_node23_pred0demand
  None: (x[price,0] - 20.1146255836938)/5.775951226575475*-0.2390628 + (x[x1,0] - 0.498885610277354)/0.29219144906564115*-0.42652094 + (x[x2,0] - 0.5214826797651598)/0.2892095979108203*-0.47124228 - 0.56830287  <=  v[demand,0,23,0]
Constraint component: constraint_2_layer0_node23_pred0demand
  None: v[demand,0,23,0]  <=  1000.0*v_ind[demand,0,23,0]
Constraint component: constraint_3_layer0_node23_pred0demand

In [43]:
# Inputs
x = np.array([[-1.266313, -0.405118, 0.612491]])

# Extract weights from model
state_dict = trainer.model.state_dict()
w0 = state_dict['input_layer.weight'].cpu().numpy()
b0 = state_dict['input_layer.bias'].cpu().numpy()

#w1 = state_dict['hidden_layers.0.weight'].cpu().numpy()
#b1 = state_dict['hidden_layers.0.bias'].cpu().numpy()

w_mean = state_dict['output_mean_layer.weight'].cpu().numpy()
b_mean = state_dict['output_mean_layer.bias'].cpu().numpy()

w_sd = state_dict['output_sd_layer.weight'].cpu().numpy()
b_sd = state_dict['output_sd_layer.bias'].cpu().numpy()

# Manual forward pass
def relu(x): return np.maximum(0, x)

h0 = relu(x.dot(w0.T) + b0)
#h1 = relu(h0.dot(w1.T) + b1)
mean = h0.dot(w_mean.T) + b_mean
sd = relu(h0.dot(w_sd.T) + b_sd)

print("Manual mean:", mean)
print("Manual std:", sd)

Manual mean: [[1.16346762]]
Manual std: [[0.32203757]]

In [44]:
contextual_var

           price            x1            x2
0  15.2341136747  0.3745401188  0.1851329288
1  28.1250916104  0.7319939418  0.8729458359

In [45]:
print((15.2341136747 - trainer.X_mean[0]) / trainer.X_std[0])
print((0.3745401188 - trainer.X_mean[1]) / trainer.X_std[1])
print((0.1851329288 - trainer.X_mean[2]) / trainer.X_std[2])

-0.8449711082285967
-0.425561705775379
-1.1629965028645957

In [46]:
row = pd.DataFrame([{
    'price': 14.838617787184095,
    'x1': 0.7319939418,
    'x2': 0.8729458359,
}])

row = row.reindex(sorted(row.columns), axis=1)

def preict_one_row(row):
    # Predict
    mean_pred, sd_pred = trainer.predict(row, unscale=False, scale_data=True)
    print("Mean prediction:", mean_pred)
    print("Standard deviation prediction:", sd_pred)

preict_one_row(row)

Scaling data...
Mean prediction: [[1.5440329]]
Standard deviation prediction: [[0.34075832]]

In [47]:
for n in model.N:
    print("&"*50)
    print("Establecimiento ", n)
    opt_price = value(model.x['price',n])
    total_demand = 0
    for x in range(n_sc):
        total_demand += value(model.y['demand', n, x+1])
        #print("demand: ", value(model.y['demand', 0, x+1]))
    print("Average demand: ", total_demand/n_sc)
    opt_mean = value(model.y['demand', n,'mean'])
    opt_sd = value(model.y['demand', n,'sd'])
    opt_profit = value(model.OBJ)

    print(f"Optimal profit: {opt_profit}")
    print(f"Optimal price: {opt_price}")
    print(f"Optimal mean: {opt_mean}")
    print(f"Optimal sd: {opt_sd}")
    print("&"*50)

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Establecimiento  0
Average demand:  6.198601406377272
Optimal profit: 185.46419920531778
Optimal price: 10.283496730540044
Optimal mean: 0.9293199046950089
Optimal sd: 0.2993529258543465
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Establecimiento  1
Average demand:  9.262561085583393
Optimal profit: 185.46419920531778
Optimal price: 13.141171300707246
Optimal mean: 1.919147313813751
Optimal sd: 0.3085844830622695
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&